### ISSUE TITLE
[1.8.9 ]Server Crash

### ISSUE THREAD

**Issue by michaelgaultjr** [Chisel-Team/Chisel#125]
I have a 1.8.9 modded Server for my SMP and when i put chisel in it crashes.... when i take it out it works just fine, can you please fix this soon i really want to use this mod for my base.

**Comment by KnightMiner** [comment]
If it crashes, provide a crash report or we cannot help you.

**Comment by michaelgaultjr** [comment]
Ok

**Comment by michaelgaultjr** [comment]
@KnightMiner here is the crash log. if this changes anything i used the curse launcher to make this pack and i just copyed the mods from my local file and removed the client one side ones, it works when chisel is not in the mods file, i have also found that the blocks are missing textures, the only item that has a texture using my local mods file is the iron basic chisel.

```
---- Minecraft Crash Report ----
* ATTENTION: detected classes with unsupported format *
* DO NOT SUBMIT THIS CRASH REPORT TO FORGE *
Contact authors of the following mods: 
chisel
WARNING: coremods are present:
CoreMod (Aroma1997Core-1.8.9-1.0.3.4.b58.jar)
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
LoadingPlugin (RandomThings-MC1.8.9-3.6.2.jar)
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
Contact their authors BEFORE contacting forge
// Shall we play a game?
Time: 2/9/16 10:38 AM
Description: Exception in server tick loop
net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: team.chisel.Chisel
 at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
 at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:543)
 at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
 at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
 at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112)
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
 at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: team.chisel.Chisel
 at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
 at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:65)
 at java.lang.Class.forName0(Native Method)
 at java.lang.Class.forName(Class.java:274)
 at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:468)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
 at com.google.common.eventbus.EventBus.post(EventBus.java:275)
 at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
 at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
 at com.google.common.eventbus.EventBus.post(EventBus.java:275)
 at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
 at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:512)
 ... 5 more
Caused by: java.lang.UnsupportedClassVersionError: team/chisel/Chisel : Unsupported major.minor version 52.0
 at java.lang.ClassLoader.defineClass1(Native Method)
 at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
 at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
 at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
 ... 33 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- System Details --
Details:
 Minecraft Version: 1.8.9
 Operating System: Linux (i386) version 3.13.0-29-generic
 Java Version: 1.7.0_79, Oracle Corporation
 Java VM Version: OpenJDK Server VM (mixed mode), Oracle Corporation
 Memory: 225168224 bytes (214 MB) / 327155712 bytes (312 MB) up to 924581888 bytes (881 MB)
 JVM Flags: 0 total; 
 IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
 FML: MCP 9.19 Powered by Forge 11.15.1.1734 25 mods loaded, 25 mods active
 States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
 UC mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
 UC FML{8.0.99.99} [Forge Mod Loader] (modded.jar) 
 UC Forge{11.15.1.1734} [Minecraft Forge] (modded.jar) 
 UC Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.8.9-1.0.3.4.b58.jar) 
 UC Aroma1997CoreHelper{1.0.3.4.b58} [Aroma1997Core|Helper] (Aroma1997Core-1.8.9-1.0.3.4.b58.jar) 
 UC AromaBackup{0.0.1.1.b26} [AromaBackup] (AromaBackup-1.8.9-0.0.1.1.b26.jar) 
 UC AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.8.9-0.0.1.1.b26.jar) 
 UC bookshelfapi{2.2.9} [Bookshelf] (Bookshelf-1.8.9-2.2.9.jar) 
 UC Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
 UE chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.1.jar) 
 UC ComputerCraft{1.78} [ComputerCraft] (ComputerCraft1.78.jar) 
 UC fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
 UC Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
 UC FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
 UC FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
 UC IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
 UC mantle{1.8.9-0.7.jenkins72} [Mantle] (Mantle-1.8.9-0.7.jar) 
 UC testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
 UC neotech{2.3.4} [NeoTech] (NeoTech-1.8.9-2.3.4.jar) 
 UC fodc{1.7.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.1.jar) 
 UC RandomThings{3.6.2} [Random Things] (RandomThings-MC1.8.9-3.6.2.jar) 
 UC Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
 UC StorageDrawers{1.8.9-2.3.4} [Storage Drawers] (StorageDrawers-1.8.9-2.3.4.jar) 
 UC tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct] (TConstruct-1.8.9-2.0.2.jar) 
 UC Thaumcraft{5.1.6} [Thaumcraft] (Thaumcraft-1.8.9-5.1.6.jar) 
 Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.8.9-1.0.3.4.b58.jar)
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
LoadingPlugin (RandomThings-MC1.8.9-3.6.2.jar)
lumien.randomthings.asm.ClassTransformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
com.olafski.fastleafdecay.FldTransformer
 Pulsar/tconstruct loaded Pulses: 
  - TinkerCommons (Enabled/Forced)
  - TinkerWorld (Enabled/Not Forced)
  - TinkerTools (Enabled/Not Forced)
  - TinkerSmeltery (Enabled/Not Forced)
  - TinkerGadgets (Enabled/Not Forced)
  - TinkerOredict (Enabled/Forced)
  - TinkerIntegration (Enabled/Forced)
  - TinkerFluids (Enabled/Forced)
  - TinkerMaterials (Enabled/Forced)
  - TinkerDebug (Enabled/Not Forced)
 Profiler Position: N/A (disabled)
 Is Modded: Definitely; Server brand changed to 'fml,forge'
 Type: Dedicated Server (map_server.txt)
```

**Comment by tterrag1098** [comment]
Java 8 is required. See #123

**Comment by michaelgaultjr** [comment]
Ok thank you very much! but what would i do about a linux based system using ice tea?

**Comment by tterrag1098** [comment]
Update java? I've never used that distro but I'm sure google can help.

**Comment by michaelgaultjr** [comment]
I'm installing java8 now but i still seems to have the missing texture issue, and i have the latest version of java on my machine.
