### ISSUE TITLE
Chisel Modloader keeps attempting to load my items?

### ISSUE THREAD

**Issue by BobyTheDragon** [Chisel-Team/Chisel#301]
Hey chisel team, I'm currently building a small mod and for some odd reason chisel keeps trying to load textures off my mod (Well I think its that at least), Causing the first item of my mod to have no texture. I have tried my mod with other mods and by itself and the texture is fine and loads normally. Testing was done on forge 1.10.2-12.18.2.2125 and the mod itself was built on forge 1.10.2-12.18.2.2099.

When minecraft boots console spits this out:
`Exception loading model for variant bobyex:ItemIronShard#inventory, normal location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception checking if model bobyex:item/ItemIronShard can be loaded with loader team.chisel.client.render.ModelLoaderChisel@19cb3f, skipping`

I have no idea what to do, I'm new to java as I started this as a school project. My items .json file is this
`{
    "parent": "minecraft:item/generated",
 "textures": {
     "layer0": "bobyex:items/ironshard"
 }
}`

How can I tell chisel or minecraft to just load it like a normal item?

**Comment by tterrag1098** [comment]
Are you on the latest Chisel version? Could you please post the actual exception given? The way model loaders work is that each loader is fed the JSON and asked to check if it is something the loader can process. For some reason our loader is erroring on that check.

**Comment by BobyTheDragon** [comment]
Chisel version is MC1.10.2-0.0.7.3 (Its probably not the latest one as the modpack that this goes into hasnt been updated for a bit)

Here's the full exception error
`[Client thread/ERROR] [FML]: Exception loading model for variant bobyex:ItemIronShard#inventory, normal location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception checking if model bobyex:item/ItemIronShard can be loaded with loader team.chisel.client.render.ModelLoaderChisel@19cb3f, skipping
    at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:126) ~[ModelLoaderRegistry.class:?]
    at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:317) ~[ModelLoader.class:?]
    at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:170) ~[byo.class:?]
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) ~[ModelLoader.class:?]
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [byp.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132) [bxi.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113) [bxi.class:?]
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755) [bcx.class:?]
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 6 column 3
    at com.google.gson.JsonParser.parse(JsonParser.java:65) ~[JsonParser.class:?]
    at team.chisel.client.render.ModelLoaderChisel.getJSON(ModelLoaderChisel.java:70) ~[ModelLoaderChisel.class:?]
    at team.chisel.client.render.ModelLoaderChisel.accepts(ModelLoaderChisel.java:50) ~[ModelLoaderChisel.class:?]
    at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:115) ~[ModelLoaderRegistry.class:?]
    ... 17 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 6 column 3
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
    at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386) ~[JsonReader.class:?]
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:531) ~[JsonReader.class:?]
    at com.google.gson.stream.JsonReader.peek(JsonReader.java:414) ~[JsonReader.class:?]
    at com.google.gson.JsonParser.parse(JsonParser.java:60) ~[JsonParser.class:?]
    at team.chisel.client.render.ModelLoaderChisel.getJSON(ModelLoaderChisel.java:70) ~[ModelLoaderChisel.class:?]
    at team.chisel.client.render.ModelLoaderChisel.accepts(ModelLoaderChisel.java:50) ~[ModelLoaderChisel.class:?]
    at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:115) ~[ModelLoaderRegistry.class:?]
    ... 17 more
`

Then the next one says that my item has a blockstate exception which is weird because its not a block.
`[Client thread/ERROR] [FML]: Exception loading model for variant bobyex:ItemIronShard#inventory, blockstate location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model bobyex:ItemIronShard#inventory with loader VariantLoader.INSTANCE, skipping
    at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
    at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:325) ~[ModelLoader.class:?]
    at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:170) ~[byo.class:?]
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) ~[ModelLoader.class:?]
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [byp.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132) [bxi.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113) [bxi.class:?]
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755) [bcx.class:?]
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException
    at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:78) ~[bpe.class:?]
    at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1184) ~[ModelLoader$VariantLoader.class:?]
    at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
    ... 17 mor`

**Comment by Drullkus** [comment]
Would you mind showing us your resource files? We don't need pings, just the jsons.

**Comment by BobyTheDragon** [comment]
Sure, I have a lot of .json files so its a bit big.
[bobyex.zip](https://github.com/Chisel-Team/Chisel/files/598047/bobyex.zip)

**Comment by Drullkus** [comment]
That... makes no sense. @tterrag1098?

**Comment by BobyTheDragon** [comment]
Do you guys want a copy of my mod to test with chisel and see if there's something showing that i'm not noticing?

**Comment by BobyTheDragon** [comment]
@tterrag1098 @Drullkus Looks like the recent version of chisel (1.10.2-0.0.7.6) has stopped having the texture problem. I think we are all good now 👍
