### ISSUE TITLE
Right Clicking with IChisel causes crash.

### ISSUE THREAD

**Issue by Kalmeira** [Chisel-Team/Chisel#311]
Crash log:

java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:169)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by chitown3** [comment]
I am also having this issue. Running Forge 12.18.3.2185 and the latest chisel 0.7.7

http://pastebin.com/nz9CPQUV

**Comment by tterrag1098** [comment]
Could you please provide the *entire* crash log?

**Comment by ZornTaov** [comment]
here, this seems to be the same error, starts at line 7900 https://paste.ee/p/d4P8G

**Comment by tterrag1098** [comment]
This is caused by NEI patches

**Comment by xSparky911x** [comment]
So question... Who is going to fix this then? NEI or Chisel?

**Comment by tterrag1098** [comment]
I can't fix anything, I have a useless stacktrace with no way to debug. This is on NEI to at least provide a cause, but in all likelihood the fix will be from them.

**Comment by Fundryi** [comment]
What version of NEI works with Chisel?

**Comment by tterrag1098** [comment]
As far as I know, NEI has not yet fixed this issue. See https://github.com/TheCBProject/NotEnoughItems/issues/42

**Comment by AnkaraSoulreaver** [comment]
The crash occurs when there is insufficient durability in the ichisel to perform the full chisel action.  Also panels and so forth are not working.

**Comment by tterrag1098** [comment]
"panels and so forth" ?

**Comment by tterrag1098** [comment]
Also this issue was fixed a while ago

**Comment by AnkaraSoulreaver** [comment]
chiseling of blocks already placed in the world.  The chisel presents
options such as panels, pluses, and so forth.  None seem to do anything and
all function as single block.
