### ISSUE TITLE
chisel 1.8 0.0.1 test results (missing textures, invalid outputs, etc)

### ISSUE THREAD

**Issue by LlubNek** [Chisel-Team/Chisel#36]
I tested chisel in minecraft 1.8 with forge 11.14.3.1512 and NEI 1.0.5.104 (and dependencies).  These are the results:

Chisel 3 1.8 0.0.1 bugs:
- All items/blocks added by chisel are missing ENUS localised names and descriptions except White Antiblock
- Missing textures:
  - `chisel:itemChisel`
  - `chisel:end_stone:0`
  - `chisel:fantasy1:5` top
  - `chisel:gold_block:0`
  - `chisel:factory:16 - 19`
  - `chisel:fantasy:16 - 27`
- some factory blocks (16-19) don't show up in NEI
- some fantasy blocks (16-27) don't show up in NEI
- no recipe for factory blocks (you can convert between them, but if they don't exist already in world, you can't get them)
- no recipe for fantasy blocks
- no recipe for aluminum blocks (probably fine)
- no recipe for copper blocks (probably fine)
- no recipe for bronze blocks (probably fine)
- "Missing particle!" crash when breaking chiseled end stone
- needs an NEI plugin to show chisel recipes
- putting Sandstone (`minecraft:sandstone:0`), Chiseled Sandstone (`minecraft:sandstone:1`) or Smooth Sandstone (`minecraft:sandstone:2`) in the chisel yields `minecraft:sandstone:32767` (should yield sandstone variants)
- Oak Wood Planks (`minecraft:planks:0`) yields `minecraft:planks:32767` (ditto for other vanilla wood planks)
- Oak Sapling (`minecraft:sapling:0`) yields `minecraft:sapling:32767` (ditto for other vanilla saplings)
- Sand (`minecraft:sand:0`) and Red Sand (`minecraft:sand:1`) yield `minecraft:sand:32767`
- Oak Wood (`minecraft:log:0`) yields `minecraft:log:32767` and `minecraft:log2:32767` (ditto for other vanilla logs)
- Oak Leaves (`minecraft:leaves:0`) yields `minecraft:leaves:32767` and `minecraft:leaves2:32767` (ditto for other vanilla leaves)
- Glass (`minecraft:glass:0`) yields itself twice and `minecraft:stained_glass:32767`
- Chest (`minecraft:chest:0`) yields itself twice and other vanilla chests (ditto for other vanilla chests)
- Chest -> Ender Chest is maybe OP
- White Stained Glass (`minecraft:stained_glass:0`) yields itself, Glass (`minecraft:glass:0`) and `minecraft:stained_glass:32767` (ditto for other vanilla stained glass)
- Glass Pane (`minecraft:glass_pane:0`) yields itself twice and `minecraft:stained_glass_pane:32767`
- Oak Wood Slab (`minecraft:wooden_slab:0`) yields `minecraft:wooden_slab:32767` (ditto for other vanilla wooden slabs)
- White Stained Glass Pane (`minecraft:stained_glass_pane:0`) yields itself, Glass (`minecraft:glass:0`) and `minecraft:stained_glass_pane:32767`
- While you can convert between different vanilla wooden stairs just fine, you can't convert slabs, doors, fences, fence gates, planks, logs, leaves or saplings due to bugs and omissions.
- Should add stone, granite and polished granite blocks since andesite and diorite are already in.
- Can't convert between sandstone, red sandstone, stone brick, nether quartz and prismarine variants due to bugs and omissions.

Here's a crash report for the particle bug:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  CCCDeobfPlugin (unknown)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.139-universal.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 06/10/15 10:03 PM
Description: Unexpected error

java.lang.RuntimeException: Missing particle!
    at net.minecraft.client.resources.model.SimpleBakedModel$Builder.func_177645_b(SourceFile:131)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:63)
    at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:1851)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1332)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1210)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1035)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.client.resources.model.SimpleBakedModel$Builder.func_177645_b(SourceFile:131)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:63)
    at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:1851)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1332)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1210)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Yorple'/2, l='MpServer', x=-527.53, y=56.00, z=-1826.25]]
    Chunk stats: MultiplayerChunkCache: 575, 575
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: -520.00,4.00,-1817.00 - World: (-520,4,-1817), Chunk: (at 8,0,7 in -33,-114; contains blocks -528,0,-1824 to -513,255,-1809), Region: (-2,-4; contains chunks -64,-128 to -33,-97, blocks -1024,0,-2048 to -513,255,-1537)
    Level time: 27085 game time, 222704 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 2 total; [EntityPlayerSP['Yorple'/2, l='MpServer', x=-527.17, y=56.00, z=-1839.24], EntityPlayerSP['Yorple'/2, l='MpServer', x=-527.53, y=56.00, z=-1826.25]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2503)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:374)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Linux (amd64) version 3.16.0-38-generic
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 225461776 bytes (215 MB) / 507453440 bytes (483 MB) up to 1597243392 bytes (1523 MB)
    JVM Flags: 5 total; -Xmx1536M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1512 6 mods loaded, 6 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1512.jar) 
    UCHIJAAAA   Forge{11.14.3.1512} [Minecraft Forge] (forge-1.8-11.14.3.1512.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.104} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-universal.jar) 
    UCHIJAAAA   chisel{@VERSION@} [Chisel 3] (Chisel_DEV-MC1.8-0.0.1.3.jar) 
    Loaded coremods (and transformers): 
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CCCDeobfPlugin (unknown)

NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.139-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
    GL info: ' Vendor: 'X.Org' Version: '3.0 Mesa 10.1.3' Renderer: 'Gallium 0.4 on AMD RV620'
    Launched Version: 1.8
    LWJGL: 2.9.1
    OpenGL: Gallium 0.4 on AMD RV620 GL version 3.0 Mesa 10.1.3, X.Org
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: No
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
```

**Comment by Drullkus** [comment]
Chisel 1.8 isn't exactly ready for use, it's in alpha

**Comment by gdude2002** [comment]
Has there been any progress on a 1.8 version? I'm not entirely sure how big the API changes were, but it does look like a big job.

**Comment by minecreatr** [comment]
There has been some progress. The Current 1.8 release is a pre alpha and is very buggy. At the moment all it has really is the rendering engine and some core blocks. The next update is going to be a big one, hence why it is taking so long. Sorry about all the bugs, but yes we are working on an update.

**Comment by tterrag1098** [comment]
We've rewritten most of the stuff this issue concerns. What hasn't been done will be incorporated into a todo list soon.
