### ISSUE TITLE
NPE when left clicking a block with any chisel

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#365]
Using Chisel ver. 1.10.2-0.0.8.12, when someone left clicks a chiselable block with a chisel, server console reports a NPE: http://pastebin.com/kFmAzFE5

Any more information you'd like?

**Comment by mrapplexz** [comment]
Same issue.

**Comment by Codazed** [comment]
Same issue. This block of text appears in console whenever left-clicking a block.
```
[00:37:16] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$LeftClickBlock@678002f1:
java.lang.NullPointerException
[00:37:16] [Server thread/ERROR] [FML]: Index: 3 Listeners:
[00:37:16] [Server thread/ERROR] [FML]: 0: NORMAL
[00:37:16] [Server thread/ERROR] [FML]: 1: ASM: ItemExchangeRod{Name=exchangeRod} onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:16] [Server thread/ERROR] [FML]: 2: ASM: vazkii.quark.tweaks.feature.KnockOnDoors@154a70a3 leftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:16] [Server thread/ERROR] [FML]: 3: ASM: class team.chisel.common.item.ChiselController onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:16] [Server thread/ERROR] [FML]: 4: ASM: class com.rwtema.extrautils2.backend.ILeftClickHandler$PacketSendLeftClick handleLeftBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:16] [Server thread/ERROR] [FML]: 5: ASM: com.amadornes.rscircuits.CommonProxy@60939993 serverBreakPrevention(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:16] [Server thread/ERROR] [FML]: 6: ASM: mod.chiselsandbits.events.EventPlayerInteract@c7fb535 interaction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:16] [Server thread/ERROR] [FML]: 7: ASM: biomesoplenty.common.handler.AchievementEventHandler@1883d0a8 onItemUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:16] [Server thread/ERROR] [FML]: 8: ASM: WayofTime.bloodmagic.util.handler.event.LivingArmourHandler@58b3a6aa onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:16] [Server thread/ERROR] [FML]: 9: ASM: WayofTime.bloodmagic.util.handler.event.GenericHandler@7be07d3f onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:16] [Server thread/ERROR] [FML]: 10: ASM: minetweaker.mc1102.ForgeEventHandler@3ba9d54b onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:16] [Server thread/ERROR] [FML]: 11: ASM: appeng.parts.PartPlacement@15484eff playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:16] [Server thread/ERROR] [FML]: 12: ASM: romelo333.notenoughwands.ForgeEventHandlers@da23f9e onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:16] [Server thread/ERROR] [FML]: 13: ASM: mcjty.rftools.ForgeEventHandlers@40cab583 onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:16] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
```

**Comment by tterrag1098** [comment]
There must be more to these logs. None of them show an actual stacktrace from chisel code.

**Comment by Codazed** [comment]
I can post the full log from my server, though it has been running since before I commented last. You may have to scroll back quite a bit.

**Comment by tterrag1098** [comment]
I just need what occurs after the `Caused by: java.lang.NullPointerException`

**Comment by Codazed** [comment]
This is what my log says for that moment:
```
[00:37:14] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$LeftClickBlock@19895696:
java.lang.NullPointerException
[00:37:14] [Server thread/ERROR] [FML/]: Index: 3 Listeners:
[00:37:14] [Server thread/ERROR] [FML/]: 0: NORMAL
[00:37:14] [Server thread/ERROR] [FML/]: 1: ASM: ItemExchangeRod{Name=exchangeRod} onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:14] [Server thread/ERROR] [FML/]: 2: ASM: vazkii.quark.tweaks.feature.KnockOnDoors@154a70a3 leftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:14] [Server thread/ERROR] [FML/]: 3: ASM: class team.chisel.common.item.ChiselController onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:14] [Server thread/ERROR] [FML/]: 4: ASM: class com.rwtema.extrautils2.backend.ILeftClickHandler$PacketSendLeftClick handleLeftBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:14] [Server thread/ERROR] [FML/]: 5: ASM: com.amadornes.rscircuits.CommonProxy@60939993 serverBreakPrevention(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:14] [Server thread/ERROR] [FML/]: 6: ASM: mod.chiselsandbits.events.EventPlayerInteract@c7fb535 interaction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:14] [Server thread/ERROR] [FML/]: 7: ASM: biomesoplenty.common.handler.AchievementEventHandler@1883d0a8 onItemUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:14] [Server thread/ERROR] [FML/]: 8: ASM: WayofTime.bloodmagic.util.handler.event.LivingArmourHandler@58b3a6aa onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:14] [Server thread/ERROR] [FML/]: 9: ASM: WayofTime.bloodmagic.util.handler.event.GenericHandler@7be07d3f onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:14] [Server thread/ERROR] [FML/]: 10: ASM: minetweaker.mc1102.ForgeEventHandler@3ba9d54b onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:14] [Server thread/ERROR] [FML/]: 11: ASM: appeng.parts.PartPlacement@15484eff playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:14] [Server thread/ERROR] [FML/]: 12: ASM: romelo333.notenoughwands.ForgeEventHandlers@da23f9e onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:14] [Server thread/ERROR] [FML/]: 13: ASM: mcjty.rftools.ForgeEventHandlers@40cab583 onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:16] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$LeftClickBlock@678002f1:
java.lang.NullPointerException
[00:37:16] [Server thread/ERROR] [FML/]: Index: 3 Listeners:
[00:37:16] [Server thread/ERROR] [FML/]: 0: NORMAL
[00:37:16] [Server thread/ERROR] [FML/]: 1: ASM: ItemExchangeRod{Name=exchangeRod} onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:16] [Server thread/ERROR] [FML/]: 2: ASM: vazkii.quark.tweaks.feature.KnockOnDoors@154a70a3 leftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:16] [Server thread/ERROR] [FML/]: 3: ASM: class team.chisel.common.item.ChiselController onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:16] [Server thread/ERROR] [FML/]: 4: ASM: class com.rwtema.extrautils2.backend.ILeftClickHandler$PacketSendLeftClick handleLeftBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:16] [Server thread/ERROR] [FML/]: 5: ASM: com.amadornes.rscircuits.CommonProxy@60939993 serverBreakPrevention(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:16] [Server thread/ERROR] [FML/]: 6: ASM: mod.chiselsandbits.events.EventPlayerInteract@c7fb535 interaction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[00:37:16] [Server thread/ERROR] [FML/]: 7: ASM: biomesoplenty.common.handler.AchievementEventHandler@1883d0a8 onItemUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:16] [Server thread/ERROR] [FML/]: 8: ASM: WayofTime.bloodmagic.util.handler.event.LivingArmourHandler@58b3a6aa onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:16] [Server thread/ERROR] [FML/]: 9: ASM: WayofTime.bloodmagic.util.handler.event.GenericHandler@7be07d3f onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:16] [Server thread/ERROR] [FML/]: 10: ASM: minetweaker.mc1102.ForgeEventHandler@3ba9d54b onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:16] [Server thread/ERROR] [FML/]: 11: ASM: appeng.parts.PartPlacement@15484eff playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:16] [Server thread/ERROR] [FML/]: 12: ASM: romelo333.notenoughwands.ForgeEventHandlers@da23f9e onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[00:37:16] [Server thread/ERROR] [FML/]: 13: ASM: mcjty.rftools.ForgeEventHandlers@40cab583 onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
```

**Comment by tterrag1098** [comment]
There is still no stacktrace there that is useful.

**Comment by Codazed** [comment]
I am loading up my client to try replicating the issue again so I can send you the full output from the server console. It won't go back far enough.

**Comment by Codazed** [comment]
Unfortunately, there is no stack trace. This is literally all that appears in the server console upon left-clicking on a block with one of the chisels.
```
[17:12:16] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$LeftClickBlock@9106b7f:
java.lang.NullPointerException
[17:12:16] [Server thread/ERROR] [FML]: Index: 3 Listeners:
[17:12:16] [Server thread/ERROR] [FML]: 0: NORMAL
[17:12:16] [Server thread/ERROR] [FML]: 1: ASM: ItemExchangeRod{Name=exchangeRod} onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[17:12:16] [Server thread/ERROR] [FML]: 2: ASM: vazkii.quark.tweaks.feature.KnockOnDoors@154a70a3 leftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[17:12:16] [Server thread/ERROR] [FML]: 3: ASM: class team.chisel.common.item.ChiselController onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[17:12:16] [Server thread/ERROR] [FML]: 4: ASM: class com.rwtema.extrautils2.backend.ILeftClickHandler$PacketSendLeftClick handleLeftBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[17:12:16] [Server thread/ERROR] [FML]: 5: ASM: com.amadornes.rscircuits.CommonProxy@60939993 serverBreakPrevention(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[17:12:16] [Server thread/ERROR] [FML]: 6: ASM: mod.chiselsandbits.events.EventPlayerInteract@c7fb535 interaction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[17:12:16] [Server thread/ERROR] [FML]: 7: ASM: biomesoplenty.common.handler.AchievementEventHandler@1883d0a8 onItemUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:12:16] [Server thread/ERROR] [FML]: 8: ASM: WayofTime.bloodmagic.util.handler.event.LivingArmourHandler@58b3a6aa onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:12:16] [Server thread/ERROR] [FML]: 9: ASM: WayofTime.bloodmagic.util.handler.event.GenericHandler@7be07d3f onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:12:16] [Server thread/ERROR] [FML]: 10: ASM: minetweaker.mc1102.ForgeEventHandler@3ba9d54b onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:12:16] [Server thread/ERROR] [FML]: 11: ASM: appeng.parts.PartPlacement@15484eff playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:12:16] [Server thread/ERROR] [FML]: 12: ASM: romelo333.notenoughwands.ForgeEventHandlers@da23f9e onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:12:16] [Server thread/ERROR] [FML]: 13: ASM: mcjty.rftools.ForgeEventHandlers@40cab583 onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:12:16] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
```

**Comment by Codazed** [comment]
OK, I restarted the server, then tried again. This time, I got different output. It looks like it might be a Sponge issue, but I'm not 100% sure about that.
```
[17:47:44] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$LeftClickBlock@2ad771c6:
java.lang.NullPointerException
	at net.minecraft.util.math.RayTraceResult.<init>(RayTraceResult.java:40) ~[bbz.class:?]
	at net.minecraft.util.math.RayTraceResult.<init>(RayTraceResult.java:27) ~[bbz.class:?]
	at team.chisel.common.item.ChiselController.onPlayerInteract(ChiselController.java:47) ~[ChiselController.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_227_ChiselController_onPlayerInteract_LeftClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:637) [EventBus.class:?]
	at org.spongepowered.mod.event.SpongeForgeEventFactory.createPlayerInteractEvent(SpongeForgeEventFactory.java:805) [SpongeForgeEventFactory.class:1.10.2-2202-5.1.0-BETA-2078]
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:461) [SpongeForgeEventFactory.class:1.10.2-2202-5.1.0-BETA-2078]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:281) [SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2078]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2078]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2078]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141) [SpongeImpl.class:1.10.2-2202-5.1.0-BETA-2078]
	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventPrimary(SpongeCommonEventFactory.java:444) [SpongeCommonEventFactory.class:1.10.2-2202-5.1.0-BETA-2078]
	at org.spongepowered.common.network.PacketUtil.firePreEvents(PacketUtil.java:221) [PacketUtil.class:1.10.2-2202-5.1.0-BETA-2078]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:89) [PacketUtil.class:1.10.2-2202-5.1.0-BETA-2078]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjd000(SourceFile:539) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by Codazed** [comment]
It was obviously a Sponge issue. I removed Sponge from the installation and now everything is working fine. Sorry for the trouble.

**Comment by tterrag1098** [comment]
Could you please report it to them? I would like to find the root cause of this.
