### ISSUE TITLE
Crash Client

### ISSUE THREAD

**Issue by Andrey228322** [Chisel-Team/Chisel#415]
how to fix?
```

---- Minecraft Crash Report ----
// My bad.

Time: 22.04.17 20:32
Description: Initializing game

java.lang.NoClassDefFoundError: org/apache/commons/lang3/tuple/Triple
	at com.cricketcraft.chisel.api.rendering.TextureType$7.registerIcons(TextureType.java:194)
	at com.cricketcraft.chisel.api.rendering.TextureType$SubmapManagerDefault.registerIcons(TextureType.java:458)
	at com.cricketcraft.chisel.api.carving.VariationInfoBase.registerIcons(VariationInfoBase.java:61)
	at com.cricketcraft.chisel.api.carving.CarvableHelper.registerBlockIcons(CarvableHelper.java:201)
	at team.chisel.block.BlockCarvable.func_149651_a(BlockCarvable.java:71)
	at net.minecraft.client.renderer.texture.TextureMap.func_110573_f(TextureMap.java:458)
	at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:97)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:540)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.tuple.Triple
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 16 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.cricketcraft.chisel.api.rendering.TextureType$7.registerIcons(TextureType.java:194)
	at com.cricketcraft.chisel.api.rendering.TextureType$SubmapManagerDefault.registerIcons(TextureType.java:458)
	at com.cricketcraft.chisel.api.carving.VariationInfoBase.registerIcons(VariationInfoBase.java:61)
	at com.cricketcraft.chisel.api.carving.CarvableHelper.registerBlockIcons(CarvableHelper.java:201)
	at team.chisel.block.BlockCarvable.func_149651_a(BlockCarvable.java:71)
	at net.minecraft.client.renderer.texture.TextureMap.func_110573_f(TextureMap.java:458)
	at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:97)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:540)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 172605608 bytes (164 MB) / 313208832 bytes (298 MB) up to 1597243392 bytes (1523 MB)
	JVM Flags: 5 total; -Xmx1536M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D6 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 315M/PCIe/SSE2'
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Launched Version: ForgeOptiFine 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce 315M/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 3.3.0
	OpenGlRenderer: GeForce 315M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2
```

**Comment by tterrag1098** [comment]
First: OptiFine is not supported.

Second, see #160, this is not a Chisel bug.
