### ISSUE TITLE
Chisel provides a Client Crash

### ISSUE THREAD

**Issue by JustZerooo** [Chisel-Team/Chisel#441]
Dear developer team, 

if you try to use the chisel mod with the block of Marbel 

Marble1-100
Marble 2-101
Marble3-102

your client crashed.

```quote
java.lang.NullPointerException: Rendering item
	at net.minecraft.item.ItemStack.func_94608_d(ItemStack.java:123)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:161)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at team.chisel.client.gui.GuiChisel.func_146977_a(GuiChisel.java:143)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_94608_d(ItemStack.java:123)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:161)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)

-- Item being rendered --
Details:
	Item Type: null
	Item Aux: ~~ERROR~~ NullPointerException: null
	Item NBT: null
	Item Foil: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at team.chisel.client.gui.GuiChisel.func_146977_a(GuiChisel.java:143)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)

-- Screen render details --
Details:
	Screen name: team.chisel.client.gui.GuiChisel
	Mouse location: Scaled: (385, 188). Absolute: (771, 651)
	Screen size: Scaled: (960, 514). Absolute: (1920, 1027). Scale factor of 2

```

**Comment by tterrag1098** [comment]
Please provide your current version of Chisel.

Also, I see NEI is on the stacktrace, please uninstall NEI and reproduce.

**Comment by JustZerooo** [comment]
2.9.5.11 for 1.7.10 included in Ftb but unmodded

**Comment by tterrag1098** [comment]
1.7.10 is no longer supported.

**Comment by JustZerooo** [comment]
That is bad, very good plugin but cannot be used

**Comment by tterrag1098** [comment]
Sorry, you're using a year old version of a mod on a 2 year old version of
the game. I don't have the time or energy to maintain it. Besides, as no
one else has reported this issue, it is most likely caused by some other
mod.

**Comment by JustZerooo** [comment]
I understand that.
