### ISSUE TITLE
1.11.2 ChiselFuelHandler crash

### ISSUE THREAD

**Issue by kitsushadow** [Chisel-Team/Chisel#472]
java.lang.IllegalArgumentException: Stack can not be invalid!
        at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:440)
        at team.chisel.common.init.ChiselFuelHandler.getBurnTime(ChiselFuelHandler.java:10)
        at net.minecraftforge.fml.common.registry.GameRegistry.getFuelValue(GameRegistry.java:342)
        at nmd.primal.core.common.helper.CommonUtils.getVanillaItemBurnTime(CommonUtils.java:238)
        at nmd.primal.core.common.tiles.TileKiln.func_73660_a(TileKiln.java:118)
getVanillaItemBurnTime

**Comment by kitsushadow** [comment]
something like the below would work

```
public static int getBurnTime(ItemStack stack)
    {
        return stack.isEmpty() ? 0 : GameRegistry.getFuelValue(stack);
    }
```

**Comment by tterrag1098** [comment]
No, this is on "nmd.primal.core" whatever mod that is. IFuelHandlers shouldn't be given invalid itemstacks.
