### ISSUE TITLE
Chisel wont start

### ISSUE THREAD

**Issue by SpOngEBoB69** [Chisel-Team/Chisel#473]
When ever I start minecraft chisel wont work it says and I'm using the right version of minecraft and chisel

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Chisel (chisel)

**Comment by tterrag1098** [comment]
Whole crash log please.

**Comment by SpOngEBoB69** [comment]
It wont let me click Veiw crash report so I'm pretty sure that's the whole crash report

**Comment by KnightMiner** [comment]
You need to go into the game directory (.minecraft or the Twitch launcher equivalent) and grab it from the crash reports, the view crash report button is broken

**Comment by tterrag1098** [comment]
On a hunch, have you forgotten to install CTM?

**Comment by SpOngEBoB69** [comment]
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 7/5/17 4:52 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Chisel (chisel)
Caused by: net.minecraftforge.fml.common.MissingModsException: Mod chisel (Chisel) requires [ctm@[MC1.11.2-0.1.0.2,)]
	at team.chisel.Chisel.onConstruct(Chisel.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:582)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:233)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4527348304 bytes (4317 MB) / 6174015488 bytes (5888 MB) up to 6174015488 bytes (5888 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M -Xms2048M -Xmx3072M -Xms3072M -Xmx4096M -Xms4096M -Xmx6144M -Xms6144M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2386 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2386.jar) 
	UC	forge{13.20.1.2386} [Minecraft Forge] (forge-1.11.2-13.20.1.2386.jar) 
	UC	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UC	biomesoplenty{6.1.0.2243} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.1.0.2243-universal.jar) 
	UC	blockarmor{2.4.3} [Block Armor] (BlockArmor-1.11.2-2.4.3.jar) 
	UC	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UC	chimneys{0.7} [Chimneys] (Chimneys-0.8.jar) 
	UE	chisel{MC1.11.2-0.0.11.16} [Chisel] (Chisel-MC1.11.2-0.0.11.16.jar) 
	UC	cpm{1.0.2} [MrCrayfish's Painting Mod] (cpm-1.0.2-mc1.11.2.jar) 
	UC	cvmm{1.0} [MrCrayfish's Vending Machine Mod] (cvmm-1.0-mc1.11.2.jar) 
	UC	ptrmodellib{1.0.0} [ptrmodellib] (Decocraft-2.4.2_1.11.2.jar) 
	UC	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.11.2.jar) 
	UC	fcl{XI.23} [Fexcraft Common Library] (Fexcraft Common Library-XI.23-1.11.2.jar) 
	UC	flansmod{5.F2.0-EX} [(Fex's) FlansMod Minus] (FlansMod.Minus-5.F2.0-EX-1.11.2.jar) 
	UC	buildingblocks{1.0} [Just Build It] (JustBuildIt MC1.11.2 v1.0.jar) 
	UC	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UC	tconstruct{1.11.2-2.7.0.26} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.26.jar) 
	UC	worldedit{6.1.6} [WorldEdit] (worldedit-forge-mc1.11-6.1.6-dist.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4534' Renderer: 'Intel(R) HD Graphics 530'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

**Comment by SpOngEBoB69** [comment]
that is the crash report. Its not any of the mods interfering with it because even if I run it without any mods it says the same thing

**Comment by KnightMiner** [comment]
Try reading the second line in the stacktrace:

> Caused by: net.minecraftforge.fml.common.MissingModsException: Mod chisel (Chisel) requires [ctm@[MC1.11.2-0.1.0.2,)]

**Comment by SpOngEBoB69** [comment]
Where can I download ctm for 11.11.2

**Comment by SpOngEBoB69** [comment]
I mean 1.11.2

**Comment by SpOngEBoB69** [comment]
nvm I found it but there is only 1 version of 1.11.2 and I need MC1.11.2-0.1.0.2 and the version the download page has is MC1.10.2-0.1.0.8 and I have looked at the GitHub and Curse page

**Comment by tterrag1098** [comment]
![](http://i.imgur.com/VvWzQ3U.png)

**Comment by SpOngEBoB69** [comment]
That is just an image

**Comment by SpOngEBoB69** [comment]
it just links to here https://camo.githubusercontent.com/560c747a06881e2877112fccf2aa2686b7f3b245/687474703a2f2f692e696d6775722e636f6d2f5676577a5133552e706e67

**Comment by tterrag1098** [comment]
Yes it's an IMAGE of the curseforge downloads. Where are you looking?

**Comment by SpOngEBoB69** [comment]
oh sorry I thought that was the download link

**Comment by Drullkus** [comment]
https://minecraft.curseforge.com/projects/ctm/files

If you're still looking for it.
