### ISSUE TITLE
[issue] chisel and biomes o plenty seems to not like eachother MC1.2 Forge 14.21.1.2404 

### ISSUE THREAD

**Issue by winsrp** [Chisel-Team/Chisel#497]
crash when launching MC, not even got to home screen.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-101.jar)
  MovingWorldCoreMod (movingworld-1.12-4.340-full.jar)
  MalisisCorePlugin (malisiscore-1.12-6.0.1.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 7/18/17 2:48 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at biomesoplenty.common.handler.LeavesModelEventHandler$ModelLeaves.<init>(LeavesModelEventHandler.java:55)
	at biomesoplenty.common.handler.LeavesModelEventHandler.onModelBake(LeavesModelEventHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_226_LeavesModelEventHandler_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:367)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at biomesoplenty.common.handler.LeavesModelEventHandler$ModelLeaves.<init>(LeavesModelEventHandler.java:55)
	at biomesoplenty.common.handler.LeavesModelEventHandler.onModelBake(LeavesModelEventHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_226_LeavesModelEventHandler_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:367)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by tterrag1098** [comment]
Report this to them, it's impossible to know what the problem is because they do not null check this result: https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.12.x-7.0.x/src/main/java/biomesoplenty/common/handler/LeavesModelEventHandler.java#L40

**Comment by tterrag1098** [comment]
Unfortunately this is an unsolvable problem with how forge handles mod errors and event dispatching. BoP is getting its registry events even though its preInit has never fired.
