### ISSUE TITLE
Clicking a Abstrute Platform from Botania that disguised as Cobblestone Dent in Chisel

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [Chisel-Team/Chisel#511]
Update:This will trigger my friend's client to crash as well

```
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at team.chisel.client.render.ModelChisel.canRenderInLayer(ModelChisel.java:151)
	at team.chisel.common.asm.ChiselCoreMethods.canRenderInLayer(ChiselCoreMethods.java:26)
	at net.minecraft.block.Block.canRenderInLayer(Block.java)
	at team.chisel.common.block.BlockCarvable.canRenderInLayer(BlockCarvable.java:175)
	at vazkii.botania.client.model.PlatformModel.func_188616_a(PlatformModel.java:68)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188644_a(SourceFile:113)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:100)
	at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:668)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:47)
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175020_a(CCExtendedBlockRendererDispatcher.java:72)
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:2731)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1793)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1574)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1347)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at team.chisel.client.render.ModelChisel.canRenderInLayer(ModelChisel.java:151)
	at team.chisel.common.asm.ChiselCoreMethods.canRenderInLayer(ChiselCoreMethods.java:26)
	at net.minecraft.block.Block.canRenderInLayer(Block.java)
	at team.chisel.common.block.BlockCarvable.canRenderInLayer(BlockCarvable.java:175)
	at vazkii.botania.client.model.PlatformModel.func_188616_a(PlatformModel.java:68)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188644_a(SourceFile:113)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:100)
	at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:668)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:47)
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175020_a(CCExtendedBlockRendererDispatcher.java:72)
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:2731)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1793)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1574)
```

**Comment by tterrag1098** [comment]
Not on my end. `Block.canRenderInLayer` can NEVER be passed a null layer. Report this to Botania.
