### ISSUE TITLE
Crash on F3 when looking at chiseled marble

### ISSUE THREAD

**Issue by ArcanoxDragon** [Chisel-Team/Chisel#512]
I crashed with an `ArrayIndexOutOfBounds` error when I hit F3 while looking at some chiseled marble with the "zag" pattern. I'm running Chisel 0.0.11.26 on Minecraft 1.10.2. I'm not sure if this bug is present in the latest version but I figured I would report the stack trace regardless in case it is:

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.remove(Unknown Source)
	at net.minecraft.profiler.Profiler.func_76319_b(SourceFile:70)
	at team.chisel.ctm.client.util.ProfileUtil.end(ProfileUtil.java:26)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel.func_188616_a(AbstractCTMBakedModel.java:185)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:128)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:112)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:150)
	at net.minecraft.client.renderer.RenderItem.func_184394_a(RenderItem.java:276)
	at net.minecraft.client.renderer.RenderItem.func_184392_a(RenderItem.java:257)
	at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_184392_a(RenderItemWrapper.java:262)
	at codechicken.lib.render.item.CCRenderItem.func_184392_a(CCRenderItem.java:202)
	at net.minecraft.client.renderer.ItemRenderer.func_187462_a(ItemRenderer.java:75)
	at net.minecraft.client.renderer.ItemRenderer.func_187457_a(ItemRenderer.java:437)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:338)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:762)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1407)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:193)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:254)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
```

**Comment by tterrag1098** [comment]
Always test the latest version. This was fixed, and is explicitly mentioned in the changelog.
