### ISSUE TITLE
[1.10.2][0.0.13.29] Placing Blocks Crashes the Game.

### ISSUE THREAD

**Issue by ADventuresVDO** [Chisel-Team/Chisel#537]
Interestingly, despite being able to hold a block in my hand and see its physical form in my hand, placing one causes my game to crash.  Fiddled around with a couple different versions and it only got worse or had no effect.  Here is the crash report:

 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.2.24.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  AppleCore (AppleCore-mc1.10.2-2.2.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 9/3/17 9:00 PM
Description: Tesselating block model

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: team.chisel.ctm.api.util.RenderContextList.getRenderContext(Lteam/chisel/ctm/api/texture/ITextureType;)Lteam/chisel/ctm/api/texture/ITextureContext;
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel.func_188616_a(AbstractCTMBakedModel.java:212)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:103)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:54)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:171)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:952)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1286)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: team.chisel.ctm.api.util.RenderContextList.getRenderContext(Lteam/chisel/ctm/api/texture/ITextureType;)Lteam/chisel/ctm/api/texture/ITextureContext;
	at team.chisel.client.render.ModelChiselBlock.addAllQuads(ModelChiselBlock.java:98)
	at team.chisel.client.render.ModelChiselBlock.createModel(ModelChiselBlock.java:83)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel.lambda$getQuads$1(AbstractCTMBakedModel.java:212)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4739)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel.func_188616_a(AbstractCTMBakedModel.java:212)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:103)

-- Block model being tesselated --
Details:
	Block: chisel:glassdyedgray[variation=0]
	Block location: World: (-53,4,-390), Chunk: (at 11,0,10 in -4,-25; contains blocks -64,0,-400 to -49,255,-385), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)

-- Block being tesselated --
Details:
	Block type: ID #639 (tile.chisel.glassdyedgray // null)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-53,4,-390), Chunk: (at 11,0,10 in -4,-25; contains blocks -64,0,-400 to -49,255,-385), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)

-- Block being tesselated --
Details:
	Block type: ID #639 (tile.chisel.glassdyedgray // null)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-53,4,-390), Chunk: (at 11,0,10 in -4,-25; contains blocks -64,0,-400 to -49,255,-385), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:54)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:171)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:952)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1286)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ADventuresVDO'/49, l='MpServer', x=-52.91, y=4.00, z=-391.58]]
	Chunk stats: MultiplayerChunkCache: 579, 579
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-48,4,-385), Chunk: (at 0,0,15 in -3,-25; contains blocks -48,0,-400 to -33,255,-385), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1078 game time, 1078 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 23 total; [EntitySheep['Sheep'/32, l='MpServer', x=-0.79, y=4.00, z=-434.30], EntitySheep['Sheep'/33, l='MpServer', x=-8.39, y=4.00, z=-429.20], EntitySheep['Sheep'/34, l='MpServer', x=-7.50, y=4.00, z=-427.50], EntityCow['Cow'/35, l='MpServer', x=-15.48, y=4.00, z=-331.20], EntityPlayerSP['ADventuresVDO'/49, l='MpServer', x=-52.91, y=4.00, z=-391.58], EntityCow['Cow'/36, l='MpServer', x=-8.78, y=4.00, z=-329.15], EntityLatchedRenderer['unknown'/3781, l='MpServer', x=8.50, y=65.00, z=8.50], EntitySheep['Sheep'/37, l='MpServer', x=9.73, y=4.00, z=-452.82], EntitySheep['Sheep'/38, l='MpServer', x=15.50, y=4.00, z=-461.50], EntityCow['Cow'/40, l='MpServer', x=9.50, y=4.00, z=-318.50], EntityCow['Cow'/41, l='MpServer', x=8.50, y=4.00, z=-317.50], EntityPig['Pig'/42, l='MpServer', x=9.50, y=4.00, z=-314.50], EntitySheep['Sheep'/43, l='MpServer', x=20.50, y=4.00, z=-466.50], EntityChicken['Chicken'/44, l='MpServer', x=22.28, y=4.00, z=-457.36], EntityPig['Pig'/18, l='MpServer', x=-33.25, y=4.00, z=-400.38], EntityCow['Cow'/20, l='MpServer', x=-22.43, y=4.00, z=-467.76], EntityPig['Pig'/23, l='MpServer', x=-22.50, y=4.00, z=-388.50], EntityPig['Pig'/24, l='MpServer', x=-22.50, y=4.00, z=-390.50], EntityLatchedRenderer['unknown'/15928, l='MpServer', x=-52.91, y=4.00, z=-391.58], EntityPig['Pig'/25, l='MpServer', x=-18.78, y=4.00, z=-392.45], EntityCow['Cow'/26, l='MpServer', x=-20.50, y=4.00, z=-324.50], EntityChicken['Chicken'/27, l='MpServer', x=-21.50, y=4.00, z=-328.50], EntitySheep['Sheep'/31, l='MpServer', x=-12.18, y=4.00, z=-427.78]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/3781, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 330966960 bytes (315 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	NotEnoughItems{2.1.3.220} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.220-universal.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAA	AppleCore{2.2.2} [AppleCore] (AppleCore-mc1.10.2-2.2.2.jar) 
	UCHIJAAAA	BiblioCraft{2.2.5} [BiblioCraft] (BiblioCraft[v2.2.5][MC1.10.2].jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.10.2.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.13.29} [Chisel] (Chisel-MC1.10.2-0.0.13.29.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.9.283} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJAAAA	ctm{MC1.10.2-0.2.2.24} [CTM] (CTM-MC1.10.2-0.2.2.24.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.6.jar) 
	UCHIJAAAA	ichunutil{6.3.2} [iChunUtil] (iChunUtil-1.10.2-6.3.2.jar) 
	UCHIJAAAA	musiccraft{3.0.1} [MusicCraft] (musiccraft-3.0.1.jar) 
	UCHIJAAAA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UCHIJAAAA	personalcars{1.0} [Personal Cars] (Personal-Cars-Mod-1.10.2.jar) 
	UCHIJAAAA	portalgun{6.0.1} [PortalGun] (PortalGun-1.10.2-6.0.1.jar) 
	UCHIJAAAA	SpiceOfLife{1.3.8} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.8.jar) 
	UCHIJAAAA	bspkrsCore{at_0.9} [bspkrsCore] (Treecapitator-1.10.2-at_0.9.jar) 
	UCHIJAAAA	Treecapitator{at_0.9} [Treecapitator] (Treecapitator-1.10.2-at_0.9.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
CTMCorePlugin (CTM-MC1.10.2-0.2.2.24.jar)
  team.chisel.ctm.client.asm.CTMTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  codechicken.nei.asm.NEITransformer
AppleCore (AppleCore-mc1.10.2-2.2.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 347.88' Renderer: 'GeForce GTX 750/PCIe/SSE2'
	NotEnoughItems Invalid Fingerprint Reports: 
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.88, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor

**Comment by TehNut** [comment]
Your Chisel version is outdated.
