### ISSUE TITLE
Carving.chisel.getGroup(block,metad) crashes on tile.doorWood

### ISSUE THREAD

**Issue by Drullkus** [Chisel-Team/Chisel#55]
Trust me, it's weird. Try smacking a chisel on a door.

```
[01:18:13] [Server thread/ERROR] [FML]: Exception caught during firing event     net.minecraftforge.event.entity.player.PlayerInteractEvent@3fc1d84d:
java.lang.NullPointerException
at team.chisel.carving.GroupList$VariationWrapper.hashCode(GroupList.java:46) ~[GroupList$VariationWrapper.class:?]
at java.util.HashMap.hash(HashMap.java:362) ~[?:1.7.0_71]
at java.util.HashMap.getEntry(HashMap.java:462) ~[?:1.7.0_71]
at java.util.HashMap.get(HashMap.java:417) ~[?:1.7.0_71]
at team.chisel.carving.GroupList.getGroup(GroupList.java:241) ~[GroupList.class:?]
at team.chisel.carving.GroupList.getGroup(GroupList.java:233) ~[GroupList.class:?]
at team.chisel.carving.Carving.getGroup(Carving.java:157) ~[Carving.class:?]
at team.chisel.item.chisel.ChiselController.onInteract(ChiselController.java:85) ~[ChiselController.class:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler_9_ChiselController_onInteract_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100) [ForgeEventFactory.class:?]
at net.minecraft.server.management.ItemInWorldManager.onBlockClicked(ItemInWorldManager.java:157) [ItemInWorldManager.class:?]
at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:523) [NetHandlerPlayServer.class:?]
at net.minecraft.network.play.client.C07PacketPlayerDigging.processPacket(C07PacketPlayerDigging.java:61) [C07PacketPlayerDigging.class:?]
at net.minecraft.network.play.client.C07PacketPlayerDigging.processPacket(C07PacketPlayerDigging.java:94) [C07PacketPlayerDigging.class:?]
at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241) [NetworkManager.class:?]
at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182) [NetworkSystem.class:?]
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614) [MinecraftServer.class:?]
at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118) [IntegratedServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]
```

**Comment by tterrag1098** [comment]
This is because doors have no proper Itemblock form, so it crashes when using stack.getItem()

**Comment by Drullkus** [comment]
Outdated
