### ISSUE TITLE
Bookshelfs cause crashes when rendering Recipy

### ISSUE THREAD

**Issue by tyler489** [Chisel-Team/Chisel#553]
simular to #523 get this crash when i type Oak into JEI 
https://gist.github.com/tyler489/3d528e83d77b3a01ec769dba2e608b22

Reported to JEi Here
https://github.com/mezz/JustEnoughItems/issues/996

**Comment by P3rf3ctXZer0** [comment]
This may also relate but here
https://github.com/P3rf3ctXZer0/MC-1.12.2-TGGRS/issues/6

**Comment by croftyraider** [comment]
Same crash for me in 1.11.2:

`Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_175032_a(RenderItem.java:209)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:127)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:111)

-- Ingredient being rendered --
Details:
	Ingredient Mod: Chisel
	Ingredient Info: 1xtile.chisel.bookshelf_oak@1 chisel:bookshelf_oak
Stacktrace:
	at mezz.jei.render.GuiIngredientFast.createRenderIngredientException(GuiIngredientFast.java:407)
	at mezz.jei.render.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:115)
	at mezz.jei.render.GuiIngredientFastList.render(GuiIngredientFastList.java:170)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:141)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:174)`

**Comment by tyler489** [comment]
So is this a jei issue?

**Comment by tterrag1098** [comment]
No, a CTM update was released which should resolve this.
