### ISSUE TITLE
[1.12.1] - Invalid id 4096 - maximum id range exceeded (With Chisel)

### ISSUE THREAD

**Issue by Protheus** [Chisel-Team/Chisel#555]
**Issue**: When using the chisel version below with the rftools version, I get the crash report with error below.
Remove chisel and all works fine.

The crash reports mcjtylib & rftoolsdim are affected, reported withhim but he reported too many id's
https://github.com/McJty/McJtyLib/issues/39

-----

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:277)
at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:263)
at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:107)
at mcjty.lib.McJtyRegister.registerBlocks(McJtyRegister.java:33)
at mcjty.rftoolsdim.ForgeEventHandlers.registerBlocks(ForgeEventHandlers.java:59)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1428_ForgeEventHandlers_registerBlocks_Register.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:729)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:605)
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-----

Pastebin: https://pastebin.com/WHi6XQei

mcjtylib-1.12-2.4.4
rftoolsdim-1.12-5.05
Chisel-MC1.12-0.0.14.18
Forge: 2485

**Comment by asiekierka** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/4416

**Comment by Protheus** [comment]
tnx, got it sorted, messed up everything but now I know where too look for it.
