### ISSUE TITLE
NPE With AE2 & B:DecorativeQuartzBlocks=false

### ISSUE THREAD

**Issue by srs-bsns** [Chisel-Team/Chisel#60]
Ver: Chisel-2.9.3.9, appliedenergistics2-rv3-alpha-9

In AppliedEnergistics2.cfg, if B:DecorativeQuartzBlocks=false, the game crashes during init:

```
java.lang.NullPointerException: Cannot add variation in group AECertusQuartz for null block.
    at team.chisel.carving.Carving.addVariation(Carving.java:160)
    at team.chisel.Features$1.addBlocks(Features.java:64)
    at team.chisel.Features.loadBlocks(Features.java:2956)
    at team.chisel.Features.preInit(Features.java:3025)
    at team.chisel.Chisel.preInit(Chisel.java:133)
```

**Comment by TheCricket** [comment]
You should also be disabling the chisel feature as well. That is a dependency
