### ISSUE TITLE
Minecraft Launcher Crashing

### ISSUE THREAD

**Issue by piyushmanolkar** [Chisel-Team/Chisel#639]
Crash Report Below :-
**---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 2/17/18 4:59 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraft.block.Block.setUnlocalizedName(Ljava/lang/String;)Lnet/minecraft/block/Block;
	at team.chisel.api.block.ChiselBlockBuilder.build(ChiselBlockBuilder.java:121)
	at team.chisel.api.block.ChiselBlockBuilder$VariationBuilder.build(ChiselBlockBuilder.java:205)
	at team.chisel.Features$1.addBlocks(Features.java:96)
	at team.chisel.Features.loadBlocks(Features.java:3089)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_Features_loadBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at team.chisel.api.block.ChiselBlockBuilder.build(ChiselBlockBuilder.java:121)
	at team.chisel.api.block.ChiselBlockBuilder$VariationBuilder.build(ChiselBlockBuilder.java:205)
	at team.chisel.Features$1.addBlocks(Features.java:96)
	at team.chisel.Features.loadBlocks(Features.java:3089)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_Features_loadBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 149470016 bytes (142 MB) / 305381376 bytes (291 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version         | Source                        | Signature                                |
	|:----- |:----------------- |:--------------- |:----------------------------- |:---------------------------------------- |
	| UCH   | minecraft         | 1.12.2          | minecraft.jar                 | None                                     |
	| UCH   | mcp               | 9.42            | minecraft.jar                 | None                                     |
	| UCH   | FML               | 8.0.99.99       | forge-1.12.2-14.23.2.2611.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge             | 14.23.2.2611    | forge-1.12.2-14.23.2.2611.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | mercurius_updater | 1.0             | MercuriusUpdater-1.12.2.jar   | None                                     |
	| UCH   | ctm               | MC1.12-0.2.3.12 | CTM-MC1.12-0.2.3.12.jar       | None                                     |
	| UCH   | chisel            | MC1.12-0.1.1.27 | Chisel-MC1.12-0.1.1.27.jar    | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2869' Renderer: 'Mobile Intel(R) 4 Series Express Chipset Family'
	Launched Version: 1.12.2-forge1.12.2-14.23.2.2611
	LWJGL: 2.9.4
	OpenGL: Mobile Intel(R) 4 Series Express Chipset Family GL version 2.1.0 - Build 8.15.10.2869, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because EXT_framebuffer_object is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Pentium(R) Dual-Core CPU T4200 @ 2.00GHz**

**Comment by liach** [comment]
looks like an obfuscation issue

**Comment by piyushmanolkar** [comment]
What?

**Comment by DatrixTHLK** [comment]
Next time remember to put this inside pastebin or gist.github.com

**Comment by tterrag1098** [comment]
Yes...seems like the jar you have isn't made properly. Please redownload from the official release on CurseForge.
