### ISSUE TITLE
Custom group error [1.10.2]

### ISSUE THREAD

**Issue by EngineerXL** [Chisel-Team/Chisel#707]
Hey! I've added custom group using ModTweaker. When i chisel any block I get crash. How to fix it or put custom sound in mod using RecourceTweaker?

- Crash: _Description: Updating screen events

java.lang.AbstractMethodError: Method modtweaker/mods/chisel/ChiselHelper$CarvingGroup.getSound()Lnet/minecraft/util/SoundEvent; is abstract
	at modtweaker.mods.chisel.ChiselHelper$CarvingGroup.getSound(ChiselHelper.java)
	at team.chisel.common.carving.Carving.getSound(Carving.java:301)
	at team.chisel.common.carving.Carving.getVariationSound(Carving.java:285)
	at team.chisel.common.util.SoundUtil.getSound(SoundUtil.java:25)
	at team.chisel.common.util.SoundUtil.playSound(SoundUtil.java:33)
	at team.chisel.client.gui.PacketChiselButton.chiselAll(PacketChiselButton.java:116)
	at team.chisel.client.gui.GuiHitechChisel.func_146284_a(GuiHitechChisel.java:494)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:460)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:320)
	at team.chisel.client.gui.GuiChisel.func_73864_a(GuiChisel.java:58)
	at team.chisel.client.gui.GuiHitechChisel.func_73864_a(GuiHitechChisel.java:448)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)_

**Comment by tterrag1098** [comment]
ModTweaker needs to update their version of the API or properly add a dependency restriction on chisel.
