### ISSUE TITLE
chisel causing issues with server

### ISSUE THREAD

**Issue by diablo184** [Chisel-Team/Chisel#710]
chisel is as far as i understand doing some weird things with forge that it should not be any idea how to fix. 
[debug.zip](https://github.com/Chisel-Team/Chisel/files/2177255/debug.zip)

java.lang.ClassCastException: it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap cannot be cast to gnu.trove.map.hash.TIntObjectHashMap
    at team.chisel.ctm.client.model.ModelUtil.lambda$getMesh$0(ModelUtil.java:51)
    at team.chisel.ctm.client.model.ModelUtil$$Lambda$1195/1768680984.apply(Unknown Source)
    at java.util.Optional.map(Optional.java:215)
    at team.chisel.ctm.client.model.ModelUtil.getMesh(ModelUtil.java:51)
    at team.chisel.ctm.client.model.AbstractCTMBakedModel$Overrides.handleItemState(AbstractCTMBakedModel.java:84)

**Comment by tterrag1098** [comment]
Your CTM is out of date
