### ISSUE TITLE
[Chisel]: java.lang.NullPointerException. Cannot re-enter the archive or new game after return to the main menu

### ISSUE THREAD

**Issue by AmalaNever** [Chisel-Team/Chisel#814]
when i save my archive, i try to enter another archive or re-enter the world i save, it doesn't work.

[latest.log](https://github.com/Chisel-Team/Chisel/files/4253954/latest.log)

**Comment by tterrag1098** [comment]
Good find, I messed up the logging in the JEI plugin. Could you try loading up with this version and post the log? It should post the actual error now.

http://assets.tterrag.com/Chisel_DEV-MC1.12.2-1.0.1.ec242ef.jar

**Comment by AmalaNever** [comment]
> 
> 
> Good find, I messed up the logging in the JEI plugin. Could you try loading up with this version and post the log? It should post the actual error now.
> 
> http://assets.tterrag.com/Chisel_DEV-MC1.12.2-1.0.1.ec242ef.jar

Thank you, I will try and and post the log.

**Comment by AmalaNever** [comment]
> 
> 
> Good find, I messed up the logging in the JEI plugin. Could you try loading up with this version and post the log? It should post the actual error now.
> 
> http://assets.tterrag.com/Chisel_DEV-MC1.12.2-1.0.1.ec242ef.jar

This is the log,  it has no find NullPointer now, but I still has the problem of  re-enter the save. 
High probability is not the problem with Chisel. 
Thank you for your help!
[latest.log](https://github.com/Chisel-Team/Chisel/files/4359226/latest.log)

**Comment by tterrag1098** [comment]
That's not the complete log.

**Comment by AmalaNever** [comment]
[logs.zip](https://github.com/Chisel-Team/Chisel/files/4419394/logs.zip)

**Comment by PolyacovYury** [comment]
```
[Client thread/ERROR]: Exception getting recipe wrappers:
java.lang.NullPointerException: null
	at team.chisel.common.integration.jei.ChiselRecipeRegistryPlugin.getRecipeWrappers(ChiselRecipeRegistryPlugin.java:73) [ChiselRecipeRegistryPlugin.class:?]
	at mezz.jei.recipes.RecipeRegistryPluginSafeWrapper.lambda$getRecipeWrappers$1(RecipeRegistryPluginSafeWrapper.java:30) [RecipeRegistryPluginSafeWrapper.class:?]
	at mezz.jei.recipes.RecipeRegistryPluginSafeWrapper$$Lambda$1350/0000000000000000.get(Unknown Source) [RecipeRegistryPluginSafeWrapper.class:?]
	at mezz.jei.recipes.RecipeRegistryPluginSafeWrapper.callPluginMethod(RecipeRegistryPluginSafeWrapper.java:42) [RecipeRegistryPluginSafeWrapper.class:?]
	at mezz.jei.recipes.RecipeRegistryPluginSafeWrapper.getRecipeWrappers(RecipeRegistryPluginSafeWrapper.java:30) [RecipeRegistryPluginSafeWrapper.class:?]
	at mezz.jei.recipes.RecipeRegistry.getRecipeWrappers(RecipeRegistry.java:579) [RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.getRecipeCategories(RecipeRegistry.java:557) [RecipeRegistry.class:?]
	at wanion.jeihider.JEIHider.onRuntimeAvailable(JEIHider.java:77) [JEIHider.class:?]
	at mezz.jei.startup.JeiStarter.sendRuntime(JeiStarter.java:233) [JeiStarter.class:?]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:115) [JeiStarter.class:?]
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136) [ProxyCommonClient.class:?]
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55) [JustEnoughItems.class:?]
// a bunch of lines snipped
```

**Comment by gwynhefar** [comment]
I'm having the exact same error using 1.0.2.45 on 1.12.2.  Did it ever get fixed?
