### ISSUE TITLE
MC crashed after converting Diorite into Disordered Tiles form

### ISSUE THREAD

**Issue by PlemGitHub** [Chisel-Team/Chisel#835]
The title. There was one block to convert. I clicked Disordered Tile and then MC crashed.

Crash report is here:

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2020-06-02 09:28:24 MSK
Description: Updating screen events

java.lang.IndexOutOfBoundsException: Index: 91, Size: 46
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.minecraft.inventory.Container.slotClick(Container.java:356)
    at net.minecraft.client.multiplayer.PlayerControllerMP.windowClick(PlayerControllerMP.java:566)
    at net.minecraft.client.gui.inventory.GuiContainer.handleMouseClick(GuiContainer.java:638)
    at net.minecraft.client.gui.inventory.GuiContainer.checkHotbarKeys(GuiContainer.java:671)
    at net.minecraft.client.gui.inventory.GuiContainer.keyTyped(GuiContainer.java:648)
    at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:558)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:512)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected screen --
  Screen name: ~~ERROR~~ NullPointerException: null

-- Affected level --
  Level name: MpServer
  All players: 1 total; [GCEntityClientPlayerMP['Plem'/703079, l='MpServer', x=395.47, y=66.00, z=249.73]]
  Chunk stats: MultiplayerChunkCache: 289, 289
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (-168,64,248), Chunk: (at 8,4,8 in -11,15; contains blocks -176,0,240 to -161,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 1484247 game time, 1755299 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 16 total; [EntityItem['item.tile.traverse:fir_sapling'/704012, l='MpServer', x=399.13, y=66.00, z=250.88], EntityItem['item.tile.traverse:fir_sapling'/704897, l='MpServer', x=381.88, y=65.94, z=258.79], EntityPig['Pig'/703147, l='MpServer', x=321.78, y=70.00, z=308.51], EntitySheep['Sheep'/703163, l='MpServer', x=443.27, y=80.00, z=240.48], EntitySheep['Sheep'/703164, l='MpServer', x=375.59, y=67.00, z=183.45], EntitySheep['Sheep'/703154, l='MpServer', x=469.50, y=76.00, z=184.19], EntitySheep['Sheep'/703155, l='MpServer', x=474.27, y=73.00, z=173.50], EntityChicken['Chicken'/703168, l='MpServer', x=328.44, y=65.00, z=244.17], EntityItem['item.tile.traverse:fir_sapling'/704708, l='MpServer', x=391.28, y=78.00, z=254.45], EntityItem['item.tile.traverse:fir_sapling'/704986, l='MpServer', x=394.07, y=64.00, z=241.81], EntityItem['item.tile.dirt.default'/704984, l='MpServer', x=397.88, y=65.00, z=256.70], GCEntityClientPlayerMP['Plem'/703079, l='MpServer', x=395.47, y=66.00, z=249.73], EntityLatchedRenderer['unknown'/703081, l='MpServer', x=8.50, y=65.00, z=8.50], EntityItem['item.tile.traverse:fir_sapling'/704636, l='MpServer', x=399.39, y=84.00, z=252.68], EntityItem['item.tile.traverse:fir_sapling'/705137, l='MpServer', x=398.02, y=78.00, z=247.52], EntityItem['item.tile.chisel.granite'/704885, l='MpServer', x=393.86, y=64.00, z=242.88]]
  Retry entities: 1 total; [EntityLatchedRenderer['unknown'/703081, l='MpServer', x=8.50, y=65.00, z=8.50]]
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_251, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3746904888 bytes (3573 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
  JVM Flags: 5 total; -Xms6144m -Xmx6144m -XX:+UseG1GC -XX:MaxGCPauseMillis=4 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 118 mods loaded, 118 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                | Version           | Source                                          | Signature                                |
       |:------ |:--------------------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                         | 1.12.2            | minecraft.jar                                   | None                                     |
       | LCHIJA | mcp                               | 9.42              | minecraft.jar                                   | None                                     |
       | LCHIJA | FML                               | 8.0.99.99         | modpack.jar                                     | None                                     |
       | LCHIJA | forge                             | 14.23.5.2847      | modpack.jar                                     | None                                     |
       | LCHIJA | ivtoolkit                         | 1.3.3-1.12        | minecraft.jar                                   | None                                     |
       | LCHIJA | micdoodlecore                     |                   | minecraft.jar                                   | None                                     |
       | LCHIJA | smoothfontcore                    | mc1.12.2-2.1.1    | minecraft.jar                                   | None                                     |
       | LCHIJA | xaerominimap_core                 | 1.12.2-1.0        | minecraft.jar                                   | None                                     |
       | LCHIJA | openmodscore                      | 0.12.2            | minecraft.jar                                   | None                                     |
       | LCHIJA | foamfixcore                       | 7.7.4             | minecraft.jar                                   | None                                     |
       | LCHIJA | randompatches                     | 1.12.2-1.21.0.0   | randompatches-1.12.2-1.21.0.0.jar               | None                                     |
       | LCHIJA | smoothfont                        | mc1.12.2-2.1.1    | SmoothFont-mc1.12.2-2.1.1.jar                   | None                                     |
       | LCHIJA | ctm                               | MC1.12.2-1.0.1.30 | CTM-MC1.12.2-1.0.1.30.jar                       | None                                     |
       | LCHIJA | appliedenergistics2               | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHIJA | attributefix                      | 1.0.10            | AttributeFix-1.12.2-1.0.10.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | jei                               | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                       | None                                     |
       | LCHIJA | quark                             | r1.6-178          | Quark-r1.6-178.jar                              | None                                     |
       | LCHIJA | autoreglib                        | 1.3-32            | AutoRegLib-1.3-32.jar                           | None                                     |
       | LCHIJA | bno                               | 1.12.2-1.0.4.0    | BasicNetherOres-1.12.2-1.0.4.0.jar              | None                                     |
       | LCHIJA | battletowers                      | 1.6.5             | BattleTowers-1.12.2_1.6.5.jar                   | None                                     |
       | LCHIJA | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                          | None                                     |
       | LCHIJA | bedrockores                       | 1.2.7.42          | Bedrock+Ores-MC1.12-1.2.7.42.jar                | None                                     |
       | LCHIJA | bookshelf                         | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | bspkrscore                        | 7.6.0.1           | bspkrsCore-universal-7.6.0.1.jar                | None                                     |
       | LCHIJA | buildcraftlib                     | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                    | None                                     |
       | LCHIJA | buildcraftcore                    | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                    | None                                     |
       | LCHIJA | buildcraftbuilders                | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                    | None                                     |
       | LCHIJA | buildcrafttransport               | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                    | None                                     |
       | LCHIJA | buildcraftsilicon                 | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                    | None                                     |
       | LCHIJA | crafttweaker                      | 4.1.20            | CraftTweaker2-1.12-4.1.20.jar                   | None                                     |
       | LCHIJA | buildcraftcompat                  | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                    | None                                     |
       | LCHIJA | buildcraftenergy                  | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                    | None                                     |
       | LCHIJA | buildcraftfactory                 | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                    | None                                     |
       | LCHIJA | buildcraftrobotics                | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                    | None                                     |
       | LCHIJA | cctweaked                         | 1.86.2            | cc-tweaked-1.12.2-1.86.2.jar                    | None                                     |
       | LCHIJA | computercraft                     | 1.86.2            | cc-tweaked-1.12.2-1.86.2.jar                    | None                                     |
       | LCHIJA | chesttransporter                  | 2.8.8             | ChestTransporter-1.12.2-2.8.8.jar               | None                                     |
       | LCHIJA | chisel                            | MC1.12.2-1.0.1.44 | Chisel-MC1.12.2-1.0.1.44.jar                    | None                                     |
       | LCHIJA | codechickenlib                    | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | redstoneflux                      | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cofhcore                          | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar          | None                                     |
       | LCHIJA | cofhworld                         | 1.3.1             | CoFHWorld-1.12.2-1.3.1.7-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | ctgui                             | 1.0.0             | CraftTweaker2-1.12-4.1.20.jar                   | None                                     |
       | LCHIJA | crafttweakerjei                   | 2.0.3             | CraftTweaker2-1.12-4.1.20.jar                   | None                                     |
       | LCHIJA | defaultoptions                    | 9.2.8             | DefaultOptions_1.12.2-9.2.8.jar                 | None                                     |
       | LCHIJA | dimdoors                          | 3.0.9+287         | DimensionalDoors-3.0.9-287.jar                  | None                                     |
       | LCHIJA | dungeontactics                    | DT-0.16.6         | DungeonTactics-1.12.2-0.16.6.jar                | None                                     |
       | LCHIJA | eplus                             | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | enchdesc                          | 1.1.15            | EnchantmentDescriptions-1.12.2-1.1.15.jar       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | endercore                         | 1.12.2-0.5.73     | EnderCore-1.12.2-0.5.73.jar                     | None                                     |
       | LCHIJA | thermalfoundation                 | 2.6.3             | ThermalFoundation-1.12.2-2.6.3.27-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalexpansion                  | 5.5.4             | ThermalExpansion-1.12.2-5.5.4.43-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | enderio                           | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderiointegrationtic             | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderiobase                       | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderioconduits                   | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderioconduitsappliedenergistics | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderioconduitsopencomputers      | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderioconduitsrefinedstorage     | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderiointegrationforestry        | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | mantle                            | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                        | None                                     |
       | LCHIJA | twilightforest                    | 3.10.1013         | twilightforest-1.12.2-3.10.1013-universal.jar   | None                                     |
       | LCHIJA | tconstruct                        | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                | None                                     |
       | LCHIJA | enderiointegrationticlate         | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | ftblib                            | 5.4.7.0           | FTBLib-5.4.7.0.jar                              | None                                     |
       | LCHIJA | enderiomachines                   | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderiopowertools                 | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderstorage                      | 2.4.6.137         | EnderStorage-1.12.2-2.4.6.137-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | energyconverters                  | 1.3.6.24          | energyconverters_1.12.2-1.3.6.24.jar            | None                                     |
       | LCHIJA | extrautils2                       | 1.0               | extrautils2-1.12-1.9.9.jar                      | None                                     |
       | LCHIJA | foamfix                           | 0.10.10-1.12.2    | foamfix-0.10.10-1.12.2.jar                      | None                                     |
       | LCHIJA | forgelin                          | 1.8.4             | Forgelin-1.8.4.jar                              | None                                     |
       | LCHIJA | forgemultipartcbe                 | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | microblockcbe                     | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
       | LCHIJA | minecraftmultipartcbe             | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
       | LCHIJA | ic2                               | 2.8.1001          | IC2Classic+1.12-1.5.4.5.jar                     | None                                     |
       | LCHIJA | galacticraftcore                  | 4.0.2.244         | GalacticraftCore-1.12.2-4.0.2.244.jar           | None                                     |
       | LCHIJA | galacticraftplanets               | 4.0.2.244         | Galacticraft-Planets-1.12.2-4.0.2.244.jar       | None                                     |
       | LCHIJA | helpfixer                         | 1.12.1-1.5.18     | HelpFixer-1.12.1-1.5.18.jar                     | None                                     |
       | LCHIJA | placebo                           | 1.5.1             | Placebo-1.12.2-1.5.1.jar                        | None                                     |
       | LCHIJA | hexxitgear                        | 2.8.0             | Hexxit+Gear-1.12.2-2.8.0.jar                    | None                                     |
       | LCHIJA | waila                             | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
       | LCHIJA | ic2-classic-spmod                 | 0.0.0.0           | IC2Classic+1.12-1.5.4.5.jar                     | None                                     |
       | LCHIJA | ichunutil                         | 7.2.2             | iChunUtil-1.12.2-7.2.2.jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | teslacorelib                      | 1.0.17            | tesla-core-lib-1.12.2-1.0.17.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | industrialforegoing               | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.12.13-237.jar      | None                                     |
       | LCHIJA | infernalmobs                      | 1.7.6             | InfernalMobs-1.12.1.jar                         | None                                     |
       | LCHIJA | inventorysorter                   | 1.13.3+57         | inventorysorter-1.12.2-1.13.3+57.jar            | None                                     |
       | LCHIJA | ironchest                         | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                 | None                                     |
       | LCHIJA | jrftl                             | 1.1               | JRFTL[1.12.2]-1.1.jar                           | None                                     |
       | LCHIJA | laggoggles                        | FAT-1.12.2-4.9    | LagGoggles-FAT-1.12.2-4.9.jar                   | None                                     |
       | LCHIJA | mcmultipart                       | 2.5.3             | MCMultiPart-2.5.3.jar                           | None                                     |
       | LCHIJA | natura                            | 1.12.2-4.3.2.69   | natura-1.12.2-4.3.2.69.jar                      | None                                     |
       | LCHIJA | recipehandler                     | 0.13              | NoMoreRecipeConflict-0.13(1.12.2).jar           | None                                     |
       | LCHIJA | openmods                          | 0.12.2            | OpenModsLib-1.12.2-0.12.2.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | openblocks                        | 1.8.1             | OpenBlocks-1.12.2-1.8.1.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | quacklib                          | 2.2.5             | quacklib-2.2.5.jar                              | None                                     |
       | LCHIJA | railcraft                         | 12.0.0            | railcraft-12.0.0.jar                            | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCHIJA | reccomplex                        | 1.4.8.2           | RecurrentComplex-1.4.8.2.jar                    | None                                     |
       | LCHIJA | redstonearsenal                   | 2.6.3             | RedstoneArsenal-1.12.2-2.6.3.18-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | redwoods                          | 1.2.2             | Redwoods-1.12-1.2.2.jar                         | None                                     |
       | LCHIJA | reforged                          | 0.7.5             | Reforged-0.7.5-1.12+.jar                        | None                                     |
       | LCHIJA | xreliquary                        | 1.12.2-1.3.4.796  | Reliquary-1.12.2-1.3.4.796.jar                  | None                                     |
       | LCHIJA | rswires                           | 1.0               | rswires-3.0.1.jar                               | None                                     |
       | LCHIJA | thermaldynamics                   | 2.5.5             | ThermalDynamics-1.12.2-2.5.5.21-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | simplyjetpacks                    | 2.2.14.67         | SimplyJetpacks2-1.12.2-2.2.14.67.jar            | None                                     |
       | LCHIJA | soulshardsrespawn                 | 1.12.2-1.1.1-13   | SoulShardsRespawn-1.12.2-1.1.1-13.jar           | None                                     |
       | LCHIJA | torohealthmod                     | 1.12.2-11         | torohealth-1.12.2-11.jar                        | None                                     |
       | LCHIJA | traverse                          | 1.6.0             | Traverse-1.12.2-1.6.0-69.jar                    | None                                     |
       | LCHIJA | treecapitator                     | 1.43.0            | TreeCapitator-client-1.43.0.jar                 | None                                     |
       | LCHIJA | vanillafix                        | 1.0.10-SNAPSHOT   | VanillaFix-1.0.10-99.jar                        | None                                     |
       | LCHIJA | wanionlib                         | 1.12.2-2.4        | WanionLib-1.12.2-2.4.jar                        | None                                     |
       | LCHIJA | xaerominimap                      | 20.5.2            | Xaeros_Minimap_20.5.2_Forge_1.12.jar            | None                                     |
       | LCHIJA | xaeroworldmap                     | 1.5.6             | XaerosWorldMap_1.5.6_Forge_1.12.jar             | None                                     |
       | LCHIJA | yabba                             | 1.1.2.54          | YABBA-1.1.2.54.jar                              | None                                     |
       | LCHIJA | reauth                            | 3.6.0             | reauth-3.6.0.jar                                | daba0ec4df71b6da841768c49fb873def208a1e3 |
       | LCHIJA | teslacorelib_registries           | 1.0.17            | tesla-core-lib-1.12.2-1.0.17.jar                | None                                     |
       | LCHIJA | unidict                           | 1.12.2-2.9.6      | UniDict-1.12.2-2.9.6.jar                        | None                                     |
  Loaded coremods (and transformers): Quark Plugin (Quark-r1.6-178.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      LoadingPlugin (Xaeros_Minimap_20.5.2_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.1.jar)
                                        bre.smoothfont.asm.Transformer
                                      RandomPatches (randompatches-1.12.2-1.21.0.0.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
  GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4815' Renderer: 'Intel(R) HD Graphics 630'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - wailaIntegration (Enabled/Not Forced)
                                   - quarkIntegration (Enabled/Not Forced)
  Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced)
                               - NaturaOverworld (Enabled/Not Forced)
                               - NaturaNether (Enabled/Not Forced)
                               - NaturaDecorative (Enabled/Not Forced)
                               - NaturaTools (Enabled/Not Forced)
                               - NaturaEntities (Enabled/Not Forced)
                               - NaturaOredict (Enabled/Forced)
                               - NaturaWorld (Enabled/Not Forced)
  Ender IO: No known problems detected.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  AE2 Integration: IC2:ON, RC:ON, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
  Suspected Mods: Unknown
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
  LWJGL: 2.9.4
  OpenGL: Intel(R) HD Graphics 630 GL version 4.5.0 - Build 22.20.16.4815, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by tterrag1098** [comment]
This doesn't even mention chisel...is it consistently reproduceable? Can you make it happen with only chisel installed?

**Comment by PlemGitHub** [comment]
> This doesn't even mention chisel...is it consistently reproduceable? Can you make it happen with only chisel installed?

Well, as i mentioned, i used Chisel tool. If this mod is not the reason - then i can't tell something more about it.
No, it happened once.
