### ISSUE TITLE
When I remove Chisel from game, I get the "cricketcraft" error

### ISSUE THREAD

**Issue by Mremenar** [Chisel-Team/Chisel#852]
Hi,
How do I remove Chisel?
I tried removing Chisel from my Minecraft.  I play 1.7.10 because I love the mods for that version.  I pulled Chisel in an attempt to "lighten the load" and crashed at game start with the following error report:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 11/22/20 2:51 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/cricketcraft/chisel/api/carving/ICarvingVariation
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/cricketcraft/chisel/api/carving/ICarvingVariation
	at fr.dbrown55.concrete.Main.onPostInit(Main.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	... 10 more
Caused by: java.lang.ClassNotFoundException: com.cricketcraft.chisel.api.carving.ICarvingVariation
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1813393504 bytes (1729 MB) / 2986344448 bytes (2848 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 73 mods loaded, 73 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJ	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJ	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJ	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJ	FastCraft{1.23} [FastCraft] (FastCraft-Mod-1.7.10.jar) 
	UCHIJ	AncientWarfare{2.4.114-beta-MC1.7.10} [Ancient Warfare Core] (Ancient-Warfare-Mod-1.7.10.jar) 
	UCHIJ	AncientWarfareAutomation{2.4.114-beta-MC1.7.10} [Ancient Warfare Automation] (Ancient-Warfare-Mod-1.7.10.jar) 
	UCHIJ	AncientWarfareNEIPlugin{2.4.114-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (Ancient-Warfare-Mod-1.7.10.jar) 
	UCHIJ	AncientWarfareNpc{2.4.114-beta-MC1.7.10} [Ancient Warfare NPCs] (Ancient-Warfare-Mod-1.7.10.jar) 
	UCHIJ	AncientWarfareStructure{2.4.114-beta-MC1.7.10} [Ancient Warfare Structures] (Ancient-Warfare-Mod-1.7.10.jar) 
	UCHIJ	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJ	aquaticabyss{1.1.1} [Aquatic Abyss] (Aquatic-Abyss-Mod-1.7.10.jar) 
	UCHIJ	gibby_dungeons{1.3} [Arcana RPG] (arcana-rpg-mod-1.7.10.jar) 
	UCHIJ	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (Archimedes-Ships-Mod-1.7.10.jar) 
	UCHIJ	bis{3.1.6} [Back in Slime Mod] (Back+In+Slime-1.7.10-3.1.6.jar) 
	UCHIJ	badmobs{1.0.1} [Bad Mobs] (BadMobs-1.0.1-1.7.10.jar) 
	UCHIJ	chocolateQuest{1.0} [Chocolate Quest] (Better-Dungeons-Mod-1.7.10.jar) 
	UCHIJ	BetterFoliage{2.0.17} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.17.jar) 
	UCHIJ	BiblioCraft{1.11.6} [BiblioCraft] (BiblioCraft[v1.11.6][MC1.7.10].jar) 
	UCHIJ	PotionIDHelper{1.0.4} [Potion ID Helper] (PotionIDHelper-1.0.4.jar) 
	UCHIJ	BrandonsCore{1.0.0.12} [Brandon's Core] (Brandons-Core-1.7.10.jar) 
	UCHIJ	brewingapi{1.2.0} [Brewing-API] (Brewing-API-1.7.2-1.2.0.jar) 
	UCHIJ	TextureGeneratorLib{0.2} [TextureGeneratorLib] (TextureGeneratorLib-1.7.10_vBeta2.jar) 
	UCHIJ	WTFCore{1.7} [WhiskyTangoFox's Core] (WTFCore-1.7.10.jar) 
	UCHIJ	CaveBiomes{1.6} [WhiskyTangoFox's CaveBiomes] (CaveBiomes-Mod-1.7.10.jar) 
	UCHIE	one_point_twelve_concrete{v 1.0} [1.12 Concrete] (Concrete-Mod-1.7.10.jar) 
	UCHIJ	deconstruction{3.0.2} [Deconstruction Table] (Deconstruction-Table-Mod-1.7.10.jar) 
	UCHIJ	dungeonpack{1.7.10-1.0} [Dungeon Pack] (Dungeon-Pack-Mod-1.7.10.jar) 
	UCHIJ	wizardry{1.1.5} [Electroblob's Wizardry] (Electroblob's+Wizardry+-+1.1.5+-+MC+1.7.10.jar) 
	UCHIJ	llibrary{1.5.1} [LLibrary] (LLibrary-1.7.10.jar) 
	UCHIJ	fossil{7.3.2} [Fossils and Archeology Revival] (fossilsarcheology-for 1.7.10.jar) 
	UCHIJ	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJ	GraviGun{4.0.0-beta} [GraviGun] (Gravity-Gun-Mod-1.7.10.jar) 
	UCHIJ	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212-Core-1.7.10.jar) 
	UCHIJ	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.7.10-1.2.7.jar) 
	UCHIJ	JoypadSplitscreenMod{1.7.10-0.21} [Joypad / SplitScreen Mod] (JoypadMod-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJ	jurassicraft{1.5.0} [JurassiCraft] (JurassiCraft-1.7.10.jar) 
	UCHIJ	lootplusplus{0.24_for_1.7} [Loot++] (Loot-Plus-Plus-Mod-1.7.10.jar) 
	UCHIJ	LovelyRobot{1.2.1} [LovelyRobot] (LovelyRobot-Mod-1.7.10.jar) 
	UCHIJ	lucky{5.1.0} [Lucky Block] (Lucky-Block-Mod-1.7.10.jar) 
	UCHIJ	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (lycanitesmobscomplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (lycanitesmobscomplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (lycanitesmobscomplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (lycanitesmobscomplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (lycanitesmobscomplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (lycanitesmobscomplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (lycanitesmobscomplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (lycanitesmobscomplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (lycanitesmobscomplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (lycanitesmobscomplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (lycanitesmobscomplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (lycanitesmobscomplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (lycanitesmobscomplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	magmaox{1.0} [Magmaox] (Magmaox+1.0+Version+1.7.10.jar) 
	UCHIJ	malisiscore{1.7.10-0.13.1} [MalisisCore] (malisiscore-1.7.10-0.13.1.jar) 
	UCHIJ	malisisdoors{1.7.10-1.12.0} [Malisis' Doors] (malisisdoors-1.7.10-1.12.0.jar) 
	UCHIJ	MapWriter{2.1.8} [MapWriter] (Mapwriter-2-Mod-1.7.10.jar) 
	UCHIJ	mdxlib{1.0.0.74} [mdxlib] (MDXLib-1.7.10.jar) 
	UCHIJ	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (Mo-Creatures-Mod-1.7.10.jar) 
	UCHIJ	cfm{3.3.6} [§6MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.3.6(1.7.10).jar) 
	UCHIJ	mam{1.7.10-1.0.2} [Myths & Monsters Mod] (myths-and-monsters-mod-1.7.10.jar) 
	UCHIJ	nevermine{1.1.1} [Nevermine] (nevermine-1.1.6h.jar) 
	UCHIJ	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.jar) 
	UCHIJ	pokeball{V0.1 - 1.7.10} [Pokeball] (Pokeball-Mod-by-grim3212-1.7.10.jar) 
	UCHIJ	prehistoricspawns{0.1} [prehistoricspawns] (PrehistoricSpawns-1.7.10-B0.2.jar) 
	UCHIJ	reccomplex{0.9.1} [Recurrent Complex] (Recurrent-Complex-Mod-1.7.10.jar) 
	UCHIJ	AS_Ruins{15.3} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UCHIJ	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimeVoid-Library-1.7.10.jar) 
	UCHIJ	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
	UCHIJ	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJ	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	UCHIJ	craftingmanager{0.7.4} [Crafting Manager] (zCraftingManager 0.7.5 mc1.7.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 457.30' Renderer: 'GeForce GTX 1660 Ti/PCIe/SSE2'

Thanks in advance for your help.
M

**Comment by tterrag1098** [comment]
> at fr.dbrown55.concrete.Main.onPostInit(Main.java:46)

Report it to this mod, not me, they are depending on a super old chisel version.
