### ISSUE TITLE
Crash - Rendering overlay

### ISSUE THREAD

**Issue by JF-Dunford** [Chisel-Team/Chisel#898]
I have a fresh install with 26 other mods. When Chisel is added the game crashes.

- Java version 1.8.0_301
- Forge version 36.2.4
- Mods listed at bottom of crash-report:

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 29/09/21 11:05 AM
Description: Rendering overlay

net.minecraftforge.fml.ModLoadingException: Chisel (chisel) encountered an error during the common_setup event phase
§7java.lang.NoClassDefFoundError: team/chisel/ctm/client/texture/ctx/OffsetProviderRegistry
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:124) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$34(ModLoader.java:332) ~[forge:?] {re:classloading}
	at java.util.HashMap.forEach(Unknown Source) ~[?:1.8.0_301] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:229) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:332) ~[forge:?] {re:classloading}
	at net.minecraftforge.client.model.ModelLoaderRegistry.onModelLoadingStart(ModelLoaderRegistry.java:88) ~[forge:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:789) ~[?:?] {re:classloading}
	at net.optifine.reflect.ReflectorMethod.callVoid(ReflectorMethod.java:217) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.model.ModelBakery.processLoading(ModelBakery.java:181) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraftforge.client.model.ModelLoader.<init>(ModelLoader.java:72) ~[forge:?] {re:classloading}
	at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:57) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:20) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?] {re:classloading,re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_301] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_301] {}
Caused by: java.lang.NoClassDefFoundError: team/chisel/ctm/client/texture/ctx/OffsetProviderRegistry
	at team.chisel.client.ClientProxy.registerModels(ClientProxy.java:28) ~[chisel:MC1.16.5-2.0.1-alpha.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_74_ClientProxy_registerModels_ModelRegistryEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.2] {re:classloading}
	... 22 more
Caused by: java.lang.ClassNotFoundException: team.chisel.ctm.client.texture.ctx.OffsetProviderRegistry
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301] {}
	at team.chisel.client.ClientProxy.registerModels(ClientProxy.java:28) ~[chisel:MC1.16.5-2.0.1-alpha.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_74_ClientProxy_registerModels_ModelRegistryEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.2] {re:classloading}
	... 22 more
	Suppressed: java.lang.ClassNotFoundException
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301] {}
		at team.chisel.client.ClientProxy.registerModels(ClientProxy.java:28) ~[chisel:MC1.16.5-2.0.1-alpha.4] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_74_ClientProxy_registerModels_ModelRegistryEvent.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.2] {re:classloading}
		at net.minecraftforge.fml.ModLoader.lambda$postEvent$34(ModLoader.java:332) ~[forge:?] {re:classloading}
		at java.util.HashMap.forEach(Unknown Source) ~[?:1.8.0_301] {}
		at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:229) ~[forge:?] {re:classloading}
		at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:332) ~[forge:?] {re:classloading}
		at net.minecraftforge.client.model.ModelLoaderRegistry.onModelLoadingStart(ModelLoaderRegistry.java:88) ~[forge:?] {re:classloading}
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
		at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
		at net.optifine.reflect.Reflector.callVoid(Reflector.java:789) ~[?:?] {re:classloading}
		at net.optifine.reflect.ReflectorMethod.callVoid(ReflectorMethod.java:217) ~[?:?] {re:classloading}
		at net.minecraft.client.renderer.model.ModelBakery.processLoading(ModelBakery.java:181) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
		at net.minecraftforge.client.model.ModelLoader.<init>(ModelLoader.java:72) ~[forge:?] {re:classloading}
		at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:57) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:20) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?] {re:classloading,re:mixin}
		at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_301] {}
		at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:1.8.0_301] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_301] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_301] {}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_301] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_301] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:124) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$34(ModLoader.java:332) ~[forge:?] {re:classloading}
	at java.util.HashMap.forEach(Unknown Source) ~[?:1.8.0_301] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:229) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:332) ~[forge:?] {re:classloading}
	at net.minecraftforge.client.model.ModelLoaderRegistry.onModelLoadingStart(ModelLoaderRegistry.java:88) ~[forge:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:807) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.4.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_301, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 371074736 bytes (353 MB) / 1917845504 bytes (1829 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 16
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m -XX:+IgnoreUnrecognizedVMOptions
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.4.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.4.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.4.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.4.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.4
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.4-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.1.2.265.jar                   |Tinkers' Construct            |tconstruct                    |3.1.2.265           |SIDED_SETU|Manifest: NOSIGNATURE
		BetterDungeons-1.16.4-1.2.jar                     |YUNG's Better Dungeons        |betterdungeons                |1.16.4-1.2          |SIDED_SETU|Manifest: NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |SIDED_SETU|Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.477-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.477   |SIDED_SETU|Manifest: NOSIGNATURE
		MekanismAdditions-1.16.5-10.0.21.448.jar          |Mekanism: Additions           |mekanismadditions             |10.0.21             |SIDED_SETU|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.121.jar                          |Just Enough Items             |jei                           |7.7.1.121           |SIDED_SETU|Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.0.21.448.jar                   |Mekanism                      |mekanism                      |10.0.21             |COMMON_SET|Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.123.jar                         |Mantle                        |mantle                        |1.6.123             |COMMON_SET|Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.16.5-5.7.3.jar                       |Journeymap                    |journeymap                    |5.7.3               |COMMON_SET|Manifest: NOSIGNATURE
		Controlling-7.0.0.24.jar                          |Controlling                   |controlling                   |7.0.0.24            |COMMON_SET|Manifest: NOSIGNATURE
		ReAuth-1.16-Forge-3.9.3.jar                       |ReAuth                        |reauth                        |3.9.3               |COMMON_SET|Manifest: 3d:06:1e:e5:da:e2:ff:ae:04:00:be:45:5b:ff:fd:70:65:00:67:0b:33:87:a6:5f:af:20:3c:b6:a1:35:ca:7e
		appliedenergistics2-8.4.1.jar                     |Applied Energistics 2         |appliedenergistics2           |8.4.1               |COMMON_SET|Manifest: 95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		StorageDrawers-1.16.3-8.3.0.jar                   |Storage Drawers               |storagedrawers                |8.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-12.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-12     |COMMON_SET|Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.2.1.jar                |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2.1        |COMMON_SET|Manifest: NOSIGNATURE
		MekanismTools-1.16.5-10.0.21.448.jar              |Mekanism: Tools               |mekanismtools                 |10.0.21             |COMMON_SET|Manifest: NOSIGNATURE
		Chisel-MC1.16.5-2.0.1-alpha.4.jar                 |Chisel                        |chisel                        |MC1.16.5-2.0.1-alpha|COMMON_SET|Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.21.448.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.21             |COMMON_SET|Manifest: NOSIGNATURE
		JEITweaker-1.16.5-1.0.1.35.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.35            |COMMON_SET|Manifest: NOSIGNATURE
		CraftTweaker-1.16.5-7.1.2.442.jar                 |CraftTweaker                  |crafttweaker                  |7.1.2.442           |COMMON_SET|Manifest: NOSIGNATURE
		ImmersivePetroleum-1.16.5-3.3.0-6.jar             |Immersive Petroleum           |immersivepetroleum            |3.3.0-6             |COMMON_SET|Manifest: NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.0.3-138.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.3-138    |COMMON_SET|Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		forge-1.16.5-36.2.4-universal.jar                 |Forge                         |forge                         |36.2.4              |COMMON_SET|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		appleskin-forge-mc1.16.x-2.1.0.jar                |AppleSkin                     |appleskin                     |mc1.16.4-2.1.0      |COMMON_SET|Manifest: NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |COMMON_SET|Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |COMMON_SET|Manifest: NOSIGNATURE
		ironchest-1.16.5-11.2.13.jar                      |Iron Chests                   |ironchest                     |1.16.5-11.2.13      |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 73178fca-ff87-4e54-92a6-d1d3fc7ede3e
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) Graphics GL version 4.6.14756 Compatibility Profile Context 20.40.40.14 27.20.14040.14001, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 5800H with Radeon Graphics 
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Enhanced Default v1.12.zip
	OpenGlVersion: 4.6.14756 Compatibility Profile Context 20.40.40.14 27.20.14040.14001
	OpenGlRenderer: AMD Radeon(TM) Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 16
```

**Comment by JF-Dunford** [comment]
LOL. Disregard. I was 100% convinced I installed CTM. But I did not. The issue has been resolved since installing CTM.
