### ISSUE TITLE
"CCL has caught an exception whilst rendering a block" when using Optifine

### ISSUE THREAD

**Issue by Khris777** [Chisel-Team/Chisel#919]
When playing the Create And Above modpack with Optifine I'm constantly getting "CCL has caught an exception whilst rendering a block" errors as soon as I enter a world.

Minecraft 1.16.5
Forge 36.2.20
Optifine 1.16.5 HD U G8

All errors (1337 errors in 5 minutes 22 seconds. Just a coincidence, really.) could be traced to two Chisel blocks according to the log:

> chisel:laboratory/wallpanel (1190, 89%)
> chisel:planks/oak/log_cabin (147, 11%)

One full log entry reads like this:

```[08:50:12] [Worker-Main-492/FATAL]: Preparing crash report with UUID c440c313-93cc-4d03-92d1-ec7a1d2e0a60
[08:50:12] [Worker-Main-492/ERROR]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:383, y:16, z:-81
  Block Class:   class team.chisel.common.block.BlockCarvable
  Registry Name: chisel:laboratory/wallpanel
  State:         Block{chisel:laboratory/wallpanel}
 Tile at position
  Tile Class:    null
  Tile Id:       null
  Tile NBT:      null
This functionality can be disabled in the CCL config file.
You can also turn off player messages in the CCL config file.

net.minecraft.crash.ReportedException: Tesselating block model
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:90) ~[?:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.renderModel(CCBlockRendererDispatcher.java:72) ~[codechickenlib:1.16.5-4.0.5.438]
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:915) ~[?:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:735) ~[?:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:192) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) [?:1.8.0_312]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) [?:1.8.0_312]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_312]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1646) [?:1.8.0_312]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) [?:1.8.0_312]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_312]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_312]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_312]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_312]
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: not enough data
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060) ~[guava-21.0.jar:?]
	at team.chisel.ctm.client.model.AbstractCTMBakedModel.getQuads(AbstractCTMBakedModel.java:177) ~[ctm:MC1.16.1-1.1.2.6]
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:143) ~[?:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:89) ~[forge:?]
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:101) ~[?:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:83) ~[?:?]
	... 13 more
Caused by: java.lang.IllegalStateException: not enough data
	at net.minecraftforge.client.model.pipeline.BakedQuadBuilder.build(BakedQuadBuilder.java:124) ~[forge:?]
	at team.chisel.ctm.client.util.Quad.rebake(Quad.java:455) ~[ctm:MC1.16.1-1.1.2.6]
	at team.chisel.ctm.client.texture.render.TexturePillar.getQuad(TexturePillar.java:108) ~[ctm:MC1.16.1-1.1.2.6]
	at team.chisel.ctm.client.texture.render.TexturePillar.transformQuad(TexturePillar.java:43) ~[ctm:MC1.16.1-1.1.2.6]
	at team.chisel.ctm.client.model.ModelBakedCTM.createModel(ModelBakedCTM.java:86) ~[ctm:MC1.16.1-1.1.2.6]
	at team.chisel.ctm.client.model.AbstractCTMBakedModel.lambda$getQuads$1(AbstractCTMBakedModel.java:177) ~[ctm:MC1.16.1-1.1.2.6]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060) ~[guava-21.0.jar:?]
	at team.chisel.ctm.client.model.AbstractCTMBakedModel.getQuads(AbstractCTMBakedModel.java:177) ~[ctm:MC1.16.1-1.1.2.6]
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:143) ~[?:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:89) ~[forge:?]
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:101) ~[?:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:83) ~[?:?]
	... 13 more```

Is this something you guys can solve? It's unclear to me if this is an issue for Chisel, Optifine, or the modpack makers.

**Comment by CitiesXL2815** [comment]
Remove Optifine and try again see if problem still exist before reporting to mod author, bc Optifine Closed Source and mods don't support Optifine anyways

Optifine Adds it's own Connected Textures which isn't compatible with modding

**Comment by Khris777** [comment]
I see, thanks. The issue doesn't happen without Optifine so I'll close this.

**Comment by tterrag1098** [comment]
Optifine should be compatible, generally. You could try disabling various features/settings, it may be one that's not enabled by default causing this.
