### ISSUE TITLE
[1.16.5] [Render Crash IChisel] 

### ISSUE THREAD

**Issue by f1den** [Chisel-Team/Chisel#950]
Mod version 2.0.1-alpha4

---- Minecraft Crash Report ---- // Hey, that tickles! Hehehe!  Time: 11/10/23 7:59 PM Description: Rendering screen  java.lang.NullPointerException: Rendering screen     at team.chisel.client.gui.GuiHitechChisel.func_230450a(GuiHitechChisel.java:367) ~[chisel:MC1.16.5-2.0.1-alpha.4] {re:classloading}     at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430a(ContainerScreen.java:88) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemborders.mixins.json:ContainerScreenMixin,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:APP:charm.mixins.json:accessor.ContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}     at team.chisel.client.gui.GuiChisel.func_230430a(GuiChisel.java:113) ~[chisel:MC1.16.5-2.0.1-alpha.4] {re:classloading}     at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:363) ~[forge-1.16.5-36.2.39-universal.jar:?] {re:classloading,re

**Comment by f1den** [comment]
https://pastebin.com/NpdZTqJs

Upd with full crashlog
